-- Qué avisa la plataforma, por qué canal y con qué texto. El catálogo de eventos notificables decide qué es suprimible y qué no; las plantillas versionadas son el texto exacto que le llega al cliente.
-- GENERADO desde seeders/minimos/15-eventos-y-plantillas.json — no editar a mano.

-- Seguridad: nunca se agrupan, nunca se suprimen y no esperan ventana de deduplicación larga. Si el aviso no sale, el usuario no se entera de que le tomaron la cuenta.
INSERT INTO evento_notificable (tipo, descripcion, categoria, es_obligatorio, prioridad, es_transaccional, permite_agrupacion, ventana_deduplicacion_min, canales_permitidos, cadena_respaldo, activo) VALUES
  ('INICIO_SESION_NUEVO_DISPOSITIVO', 'Se inició sesión desde un dispositivo no reconocido', 'SEGURIDAD', TRUE, 'CRITICA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('SEGUNDO_FACTOR_SOLICITADO', 'Código de verificación de un solo uso', 'SEGURIDAD', TRUE, 'CRITICA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('CONTRASENA_CAMBIADA', 'La contraseña de acceso fue modificada', 'SEGURIDAD', TRUE, 'ALTA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('TELEFONO_CAMBIADO', 'El teléfono de la cuenta fue modificado — se avisa al número anterior', 'SEGURIDAD', TRUE, 'CRITICA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('DISPOSITIVO_AUTORIZADO', 'Se autorizó un dispositivo nuevo para operar', 'SEGURIDAD', TRUE, 'ALTA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('CUENTA_BLOQUEADA', 'La cuenta quedó bloqueada por intentos fallidos o por decisión de riesgo', 'SEGURIDAD', TRUE, 'CRITICA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE)
ON CONFLICT (tipo) DO NOTHING;

-- Transaccionales: cada movimiento de dinero se avisa. El comprobante que el cliente guarda sale de acá.
INSERT INTO evento_notificable (tipo, descripcion, categoria, es_obligatorio, prioridad, es_transaccional, permite_agrupacion, ventana_deduplicacion_min, canales_permitidos, cadena_respaldo, activo) VALUES
  ('RECARGA_ACREDITADA', 'Se acreditó saldo en la billetera', 'TRANSACCIONAL', TRUE, 'ALTA', TRUE, FALSE, 5, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('APORTE_ACREDITADO', 'El aporte al grupo quedó acreditado y conciliado', 'TRANSACCIONAL', TRUE, 'ALTA', TRUE, FALSE, 5, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('APORTE_RECHAZADO', 'El intento de pago del aporte fue rechazado', 'TRANSACCIONAL', TRUE, 'ALTA', TRUE, FALSE, 15, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('TRANSFERENCIA_RECIBIDA', 'Recibiste saldo de otra billetera', 'TRANSACCIONAL', TRUE, 'NORMAL', TRUE, FALSE, 5, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('RETIRO_EJECUTADO', 'El retiro salió hacia la cuenta de destino', 'TRANSACCIONAL', TRUE, 'ALTA', TRUE, FALSE, 5, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('RETIRO_FALLIDO', 'El desembolso fue rechazado por el banco y el saldo volvió a la billetera', 'TRANSACCIONAL', TRUE, 'ALTA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('ENTREGA_ACREDITADA', 'Cobraste tu turno: la bolsa está acreditada', 'TRANSACCIONAL', TRUE, 'CRITICA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('REVERSO_APLICADO', 'Se reversó una operación de tu billetera', 'TRANSACCIONAL', TRUE, 'ALTA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('COMISION_COBRADA', 'Se cobró una comisión y se emitió el documento tributario', 'TRANSACCIONAL', TRUE, 'NORMAL', TRUE, TRUE, 60, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('FACTURA_EMITIDA', 'Tu factura electrónica está disponible', 'TRANSACCIONAL', TRUE, 'NORMAL', TRUE, TRUE, 1440, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE)
ON CONFLICT (tipo) DO NOTHING;

-- Cobranza: sí se agrupan y sí cuentan contra el tope de contactos por semana de la estrategia de cobranza (archivo 18).
INSERT INTO evento_notificable (tipo, descripcion, categoria, es_obligatorio, prioridad, es_transaccional, permite_agrupacion, ventana_deduplicacion_min, canales_permitidos, cadena_respaldo, activo) VALUES
  ('APORTE_POR_VENCER', 'Falta poco para el vencimiento del aporte', 'COBRANZA', FALSE, 'NORMAL', FALSE, TRUE, 720, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('APORTE_VENCIDO', 'El aporte venció y entró en mora', 'COBRANZA', TRUE, 'ALTA', FALSE, TRUE, 720, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('MORA_APLICADA', 'Se aplicó el recargo por mora previsto en el reglamento', 'COBRANZA', TRUE, 'ALTA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('COBERTURA_APLICADA', 'El fondo de garantía cubrió tu aporte y quedó una deuda a tu nombre', 'COBRANZA', TRUE, 'ALTA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('PROMESA_DE_PAGO_POR_VENCER', 'Vence la fecha que comprometiste para regularizar', 'COBRANZA', FALSE, 'NORMAL', FALSE, TRUE, 1440, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('PLAN_REGULARIZACION_APROBADO', 'Se aprobó tu plan de regularización con su cronograma', 'COBRANZA', TRUE, 'NORMAL', FALSE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE)
ON CONFLICT (tipo) DO NOTHING;

-- Regulatorios y de debido proceso: la notificación es parte del acto. Si no se probó el envío, el plazo no corre (R-PLZ).
INSERT INTO evento_notificable (tipo, descripcion, categoria, es_obligatorio, prioridad, es_transaccional, permite_agrupacion, ventana_deduplicacion_min, canales_permitidos, cadena_respaldo, activo) VALUES
  ('RECLAMO_RECIBIDO', 'Se registró tu reclamo con su código y su plazo de respuesta', 'REGULATORIA', TRUE, 'ALTA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('RECLAMO_RESUELTO', 'Hay respuesta a tu reclamo y podés recurrir a segunda instancia', 'REGULATORIA', TRUE, 'ALTA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('TARIFARIO_MODIFICADO', 'Preaviso de cambio de tarifario con la fecha desde la que rige', 'REGULATORIA', TRUE, 'ALTA', FALSE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('CONTRATO_MODIFICADO', 'Preaviso de modificación del contrato de adhesión', 'REGULATORIA', TRUE, 'ALTA', FALSE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('REVISION_KYC_REQUERIDA', 'Toca actualizar tus datos para seguir operando', 'REGULATORIA', TRUE, 'ALTA', FALSE, FALSE, 10080, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('CUENTA_RESTRINGIDA_CUMPLIMIENTO', 'Se restringió la operativa por una revisión de cumplimiento', 'REGULATORIA', TRUE, 'CRITICA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('DESCARGO_HABILITADO', 'Se te imputó un incumplimiento y tenés plazo para presentar descargo', 'REGULATORIA', TRUE, 'CRITICA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE),
  ('SANCION_NOTIFICADA', 'Se resolvió una sanción y corre el plazo de apelación', 'REGULATORIA', TRUE, 'CRITICA', TRUE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'CORREO>PUSH', TRUE)
ON CONFLICT (tipo) DO NOTHING;

-- Vida del grupo y avisos comerciales: los únicos que el usuario puede apagar sin perder información obligatoria.
INSERT INTO evento_notificable (tipo, descripcion, categoria, es_obligatorio, prioridad, es_transaccional, permite_agrupacion, ventana_deduplicacion_min, canales_permitidos, cadena_respaldo, activo) VALUES
  ('INVITACION_A_GRUPO', 'Te invitaron a un grupo de pasanaku', 'COMERCIAL', FALSE, 'NORMAL', FALSE, TRUE, 1440, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('GRUPO_COMPLETO', 'El grupo llenó sus cupos y arranca', 'COMERCIAL', FALSE, 'NORMAL', FALSE, TRUE, 1440, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('SORTEO_REALIZADO', 'Salió el orden de turnos con su semilla verificable', 'COMERCIAL', TRUE, 'ALTA', FALSE, FALSE, 0, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('TURNO_PROXIMO', 'Se acerca tu turno de cobro', 'COMERCIAL', FALSE, 'NORMAL', FALSE, TRUE, 1440, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('ACUERDO_EN_VOTACION', 'El grupo abrió una votación y falta tu voto', 'COMERCIAL', FALSE, 'NORMAL', FALSE, TRUE, 720, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('INSIGNIA_OTORGADA', 'Ganaste una insignia por tu comportamiento de pago', 'COMERCIAL', FALSE, 'BAJA', FALSE, TRUE, 10080, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE),
  ('TICKET_ACTUALIZADO', 'Hay novedades en tu consulta de soporte', 'SOPORTE', FALSE, 'BAJA', FALSE, TRUE, 240, 'IN_APP,PUSH,CORREO', 'PUSH>CORREO', TRUE)
ON CONFLICT (tipo) DO NOTHING;

-- Una plantilla por (evento, canal). Las de canal externo nacen en BORRADOR: recién pasan a APROBADA cuando el proveedor devuelve su identificador, y sin `id_plantilla_proveedor` no se pueden enviar.
INSERT INTO plantilla_mensaje (codigo, evento_id, canal, descripcion, categoria_proveedor, estado_aprobacion, id_plantilla_proveedor, activa) VALUES
  ('OTP_SEGUNDO_FACTOR_WA', (SELECT id FROM evento_notificable WHERE tipo = 'SEGUNDO_FACTOR_SOLICITADO'), 'WHATSAPP', 'Código de verificación de un solo uso por WhatsApp', 'AUTHENTICATION', 'BORRADOR', NULL, FALSE),
  ('OTP_SEGUNDO_FACTOR_SMS', (SELECT id FROM evento_notificable WHERE tipo = 'SEGUNDO_FACTOR_SOLICITADO'), 'SMS', 'Código de verificación de un solo uso por SMS', 'AUTHENTICATION', 'BORRADOR', NULL, FALSE),
  ('SEGURIDAD_SESION_NUEVA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'INICIO_SESION_NUEVO_DISPOSITIVO'), 'PUSH', 'Aviso de sesión desde dispositivo no reconocido', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('SEGURIDAD_CUENTA_BLOQUEADA_WA', (SELECT id FROM evento_notificable WHERE tipo = 'CUENTA_BLOQUEADA'), 'WHATSAPP', 'Aviso de bloqueo de cuenta con canal de contacto', 'UTILITY', 'BORRADOR', NULL, FALSE),
  ('TX_RECARGA_ACREDITADA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'RECARGA_ACREDITADA'), 'PUSH', 'Confirmación de recarga acreditada', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TX_APORTE_ACREDITADO_WA', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_ACREDITADO'), 'WHATSAPP', 'Confirmación de aporte acreditado con constancia', 'UTILITY', 'BORRADOR', NULL, FALSE),
  ('TX_APORTE_RECHAZADO_WA', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_RECHAZADO'), 'WHATSAPP', 'Aviso de pago rechazado con motivo y reintento', 'UTILITY', 'BORRADOR', NULL, FALSE),
  ('TX_ENTREGA_ACREDITADA_WA', (SELECT id FROM evento_notificable WHERE tipo = 'ENTREGA_ACREDITADA'), 'WHATSAPP', 'Aviso de bolsa acreditada con el detalle de deducciones', 'UTILITY', 'BORRADOR', NULL, FALSE),
  ('TX_RETIRO_FALLIDO_WA', (SELECT id FROM evento_notificable WHERE tipo = 'RETIRO_FALLIDO'), 'WHATSAPP', 'Aviso de retiro rechazado por el banco con devolución del saldo', 'UTILITY', 'BORRADOR', NULL, FALSE),
  ('COB_APORTE_POR_VENCER_WA', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_POR_VENCER'), 'WHATSAPP', 'Recordatorio de aporte próximo a vencer con enlace de pago', 'UTILITY', 'BORRADOR', NULL, FALSE),
  ('COB_APORTE_VENCIDO_WA', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_VENCIDO'), 'WHATSAPP', 'Aviso de aporte vencido con monto exacto y recargo', 'UTILITY', 'BORRADOR', NULL, FALSE),
  ('COB_COBERTURA_APLICADA_WA', (SELECT id FROM evento_notificable WHERE tipo = 'COBERTURA_APLICADA'), 'WHATSAPP', 'Aviso de cobertura del fondo de garantía y deuda generada', 'UTILITY', 'BORRADOR', NULL, FALSE),
  ('REG_RECLAMO_RECIBIDO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'RECLAMO_RECIBIDO'), 'CORREO', 'Acuse de reclamo con código, plazo y segunda instancia', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('REG_RECLAMO_RESUELTO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'RECLAMO_RESUELTO'), 'CORREO', 'Respuesta motivada al reclamo con vía de recurso', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('REG_DESCARGO_HABILITADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'DESCARGO_HABILITADO'), 'CORREO', 'Notificación de imputación con plazo de descargo', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('REG_TARIFARIO_MODIFICADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'TARIFARIO_MODIFICADO'), 'CORREO', 'Preaviso de cambio de tarifario', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('GRP_SORTEO_REALIZADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'SORTEO_REALIZADO'), 'PUSH', 'Aviso del sorteo con la semilla verificable', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('GRP_INVITACION_WA', (SELECT id FROM evento_notificable WHERE tipo = 'INVITACION_A_GRUPO'), 'WHATSAPP', 'Invitación a un grupo con enlace de un solo uso', 'MARKETING', 'BORRADOR', NULL, FALSE),
  ('INICIO_SESION_NUEVO_DISPOSITIVO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'INICIO_SESION_NUEVO_DISPOSITIVO'), 'IN_APP', 'Inicio de sesión desde un dispositivo nuevo', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('INICIO_SESION_NUEVO_DISPOSITIVO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'INICIO_SESION_NUEVO_DISPOSITIVO'), 'CORREO', 'Inicio de sesión desde un dispositivo nuevo', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('SEGUNDO_FACTOR_SOLICITADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'SEGUNDO_FACTOR_SOLICITADO'), 'IN_APP', 'Tu código de verificación', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('SEGUNDO_FACTOR_SOLICITADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'SEGUNDO_FACTOR_SOLICITADO'), 'PUSH', 'Tu código de verificación', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('SEGUNDO_FACTOR_SOLICITADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'SEGUNDO_FACTOR_SOLICITADO'), 'CORREO', 'Tu código de verificación', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('CONTRASENA_CAMBIADA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'CONTRASENA_CAMBIADA'), 'IN_APP', 'Tu contraseña cambió', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('CONTRASENA_CAMBIADA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'CONTRASENA_CAMBIADA'), 'PUSH', 'Tu contraseña cambió', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('CONTRASENA_CAMBIADA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'CONTRASENA_CAMBIADA'), 'CORREO', 'Tu contraseña cambió', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('TELEFONO_CAMBIADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'TELEFONO_CAMBIADO'), 'IN_APP', 'Tu teléfono cambió', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('TELEFONO_CAMBIADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'TELEFONO_CAMBIADO'), 'PUSH', 'Tu teléfono cambió', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('TELEFONO_CAMBIADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'TELEFONO_CAMBIADO'), 'CORREO', 'Tu teléfono cambió', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('DISPOSITIVO_AUTORIZADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'DISPOSITIVO_AUTORIZADO'), 'IN_APP', 'Nuevo dispositivo de confianza', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('DISPOSITIVO_AUTORIZADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'DISPOSITIVO_AUTORIZADO'), 'PUSH', 'Nuevo dispositivo de confianza', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('DISPOSITIVO_AUTORIZADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'DISPOSITIVO_AUTORIZADO'), 'CORREO', 'Nuevo dispositivo de confianza', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('CUENTA_BLOQUEADA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'CUENTA_BLOQUEADA'), 'IN_APP', 'Tu cuenta está bloqueada', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('CUENTA_BLOQUEADA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'CUENTA_BLOQUEADA'), 'PUSH', 'Tu cuenta está bloqueada', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('CUENTA_BLOQUEADA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'CUENTA_BLOQUEADA'), 'CORREO', 'Tu cuenta está bloqueada', 'AUTHENTICATION', 'APROBADA', NULL, TRUE),
  ('RECARGA_ACREDITADA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'RECARGA_ACREDITADA'), 'IN_APP', 'Recarga acreditada', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('RECARGA_ACREDITADA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'RECARGA_ACREDITADA'), 'CORREO', 'Recarga acreditada', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_ACREDITADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_ACREDITADO'), 'IN_APP', 'Aporte registrado', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_ACREDITADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_ACREDITADO'), 'PUSH', 'Aporte registrado', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_ACREDITADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_ACREDITADO'), 'CORREO', 'Aporte registrado', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_RECHAZADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_RECHAZADO'), 'IN_APP', 'No pudimos registrar tu aporte', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_RECHAZADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_RECHAZADO'), 'PUSH', 'No pudimos registrar tu aporte', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_RECHAZADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_RECHAZADO'), 'CORREO', 'No pudimos registrar tu aporte', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TRANSFERENCIA_RECIBIDA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'TRANSFERENCIA_RECIBIDA'), 'IN_APP', 'Recibiste una transferencia', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TRANSFERENCIA_RECIBIDA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'TRANSFERENCIA_RECIBIDA'), 'PUSH', 'Recibiste una transferencia', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TRANSFERENCIA_RECIBIDA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'TRANSFERENCIA_RECIBIDA'), 'CORREO', 'Recibiste una transferencia', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('RETIRO_EJECUTADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'RETIRO_EJECUTADO'), 'IN_APP', 'Retiro enviado', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('RETIRO_EJECUTADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'RETIRO_EJECUTADO'), 'PUSH', 'Retiro enviado', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('RETIRO_EJECUTADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'RETIRO_EJECUTADO'), 'CORREO', 'Retiro enviado', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('RETIRO_FALLIDO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'RETIRO_FALLIDO'), 'IN_APP', 'Tu retiro no se pudo completar', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('RETIRO_FALLIDO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'RETIRO_FALLIDO'), 'PUSH', 'Tu retiro no se pudo completar', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('RETIRO_FALLIDO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'RETIRO_FALLIDO'), 'CORREO', 'Tu retiro no se pudo completar', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('ENTREGA_ACREDITADA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'ENTREGA_ACREDITADA'), 'IN_APP', '¡Te tocó la bolsa!', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('ENTREGA_ACREDITADA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'ENTREGA_ACREDITADA'), 'PUSH', '¡Te tocó la bolsa!', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('ENTREGA_ACREDITADA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'ENTREGA_ACREDITADA'), 'CORREO', '¡Te tocó la bolsa!', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('REVERSO_APLICADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'REVERSO_APLICADO'), 'IN_APP', 'Reversamos una operación', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('REVERSO_APLICADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'REVERSO_APLICADO'), 'PUSH', 'Reversamos una operación', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('REVERSO_APLICADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'REVERSO_APLICADO'), 'CORREO', 'Reversamos una operación', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('COMISION_COBRADA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'COMISION_COBRADA'), 'IN_APP', 'Comisión cobrada', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('COMISION_COBRADA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'COMISION_COBRADA'), 'PUSH', 'Comisión cobrada', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('COMISION_COBRADA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'COMISION_COBRADA'), 'CORREO', 'Comisión cobrada', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('FACTURA_EMITIDA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'FACTURA_EMITIDA'), 'IN_APP', 'Tu factura está lista', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('FACTURA_EMITIDA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'FACTURA_EMITIDA'), 'PUSH', 'Tu factura está lista', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('FACTURA_EMITIDA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'FACTURA_EMITIDA'), 'CORREO', 'Tu factura está lista', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_POR_VENCER_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_POR_VENCER'), 'IN_APP', 'Tu aporte vence pronto', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_POR_VENCER_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_POR_VENCER'), 'PUSH', 'Tu aporte vence pronto', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_POR_VENCER_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_POR_VENCER'), 'CORREO', 'Tu aporte vence pronto', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_VENCIDO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_VENCIDO'), 'IN_APP', 'Tu aporte está vencido', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_VENCIDO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_VENCIDO'), 'PUSH', 'Tu aporte está vencido', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('APORTE_VENCIDO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'APORTE_VENCIDO'), 'CORREO', 'Tu aporte está vencido', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('MORA_APLICADA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'MORA_APLICADA'), 'IN_APP', 'Se aplicó mora a tu aporte', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('MORA_APLICADA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'MORA_APLICADA'), 'PUSH', 'Se aplicó mora a tu aporte', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('MORA_APLICADA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'MORA_APLICADA'), 'CORREO', 'Se aplicó mora a tu aporte', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('COBERTURA_APLICADA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'COBERTURA_APLICADA'), 'IN_APP', 'El fondo de garantía cubrió tu aporte', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('COBERTURA_APLICADA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'COBERTURA_APLICADA'), 'PUSH', 'El fondo de garantía cubrió tu aporte', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('COBERTURA_APLICADA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'COBERTURA_APLICADA'), 'CORREO', 'El fondo de garantía cubrió tu aporte', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('PROMESA_DE_PAGO_POR_VENCER_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'PROMESA_DE_PAGO_POR_VENCER'), 'IN_APP', 'Tu promesa de pago vence pronto', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('PROMESA_DE_PAGO_POR_VENCER_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'PROMESA_DE_PAGO_POR_VENCER'), 'PUSH', 'Tu promesa de pago vence pronto', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('PROMESA_DE_PAGO_POR_VENCER_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'PROMESA_DE_PAGO_POR_VENCER'), 'CORREO', 'Tu promesa de pago vence pronto', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('PLAN_REGULARIZACION_APROBADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'PLAN_REGULARIZACION_APROBADO'), 'IN_APP', 'Aprobamos tu plan de regularización', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('PLAN_REGULARIZACION_APROBADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'PLAN_REGULARIZACION_APROBADO'), 'PUSH', 'Aprobamos tu plan de regularización', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('PLAN_REGULARIZACION_APROBADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'PLAN_REGULARIZACION_APROBADO'), 'CORREO', 'Aprobamos tu plan de regularización', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('RECLAMO_RECIBIDO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'RECLAMO_RECIBIDO'), 'IN_APP', 'Recibimos tu reclamo', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('RECLAMO_RECIBIDO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'RECLAMO_RECIBIDO'), 'PUSH', 'Recibimos tu reclamo', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('RECLAMO_RESUELTO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'RECLAMO_RESUELTO'), 'IN_APP', 'Resolvimos tu reclamo', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('RECLAMO_RESUELTO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'RECLAMO_RESUELTO'), 'PUSH', 'Resolvimos tu reclamo', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TARIFARIO_MODIFICADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'TARIFARIO_MODIFICADO'), 'IN_APP', 'Cambian nuestras comisiones', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TARIFARIO_MODIFICADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'TARIFARIO_MODIFICADO'), 'PUSH', 'Cambian nuestras comisiones', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('CONTRATO_MODIFICADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'CONTRATO_MODIFICADO'), 'IN_APP', 'Cambia el contrato de la billetera', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('CONTRATO_MODIFICADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'CONTRATO_MODIFICADO'), 'PUSH', 'Cambia el contrato de la billetera', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('CONTRATO_MODIFICADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'CONTRATO_MODIFICADO'), 'CORREO', 'Cambia el contrato de la billetera', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('REVISION_KYC_REQUERIDA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'REVISION_KYC_REQUERIDA'), 'IN_APP', 'Necesitamos actualizar tus datos', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('REVISION_KYC_REQUERIDA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'REVISION_KYC_REQUERIDA'), 'PUSH', 'Necesitamos actualizar tus datos', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('REVISION_KYC_REQUERIDA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'REVISION_KYC_REQUERIDA'), 'CORREO', 'Necesitamos actualizar tus datos', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('CUENTA_RESTRINGIDA_CUMPLIMIENTO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'CUENTA_RESTRINGIDA_CUMPLIMIENTO'), 'IN_APP', 'Tu cuenta quedó restringida', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('CUENTA_RESTRINGIDA_CUMPLIMIENTO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'CUENTA_RESTRINGIDA_CUMPLIMIENTO'), 'PUSH', 'Tu cuenta quedó restringida', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('CUENTA_RESTRINGIDA_CUMPLIMIENTO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'CUENTA_RESTRINGIDA_CUMPLIMIENTO'), 'CORREO', 'Tu cuenta quedó restringida', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('DESCARGO_HABILITADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'DESCARGO_HABILITADO'), 'IN_APP', 'Podés presentar tu descargo', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('DESCARGO_HABILITADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'DESCARGO_HABILITADO'), 'PUSH', 'Podés presentar tu descargo', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('SANCION_NOTIFICADA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'SANCION_NOTIFICADA'), 'IN_APP', 'Te notificamos una sanción', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('SANCION_NOTIFICADA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'SANCION_NOTIFICADA'), 'PUSH', 'Te notificamos una sanción', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('SANCION_NOTIFICADA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'SANCION_NOTIFICADA'), 'CORREO', 'Te notificamos una sanción', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('INVITACION_A_GRUPO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'INVITACION_A_GRUPO'), 'IN_APP', 'Te invitaron a un pasanaku', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('INVITACION_A_GRUPO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'INVITACION_A_GRUPO'), 'PUSH', 'Te invitaron a un pasanaku', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('INVITACION_A_GRUPO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'INVITACION_A_GRUPO'), 'CORREO', 'Te invitaron a un pasanaku', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('GRUPO_COMPLETO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'GRUPO_COMPLETO'), 'IN_APP', 'El grupo se completó', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('GRUPO_COMPLETO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'GRUPO_COMPLETO'), 'PUSH', 'El grupo se completó', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('GRUPO_COMPLETO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'GRUPO_COMPLETO'), 'CORREO', 'El grupo se completó', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('SORTEO_REALIZADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'SORTEO_REALIZADO'), 'IN_APP', 'Ya hay turnos', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('SORTEO_REALIZADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'SORTEO_REALIZADO'), 'CORREO', 'Ya hay turnos', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TURNO_PROXIMO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'TURNO_PROXIMO'), 'IN_APP', 'Se acerca tu turno', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TURNO_PROXIMO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'TURNO_PROXIMO'), 'PUSH', 'Se acerca tu turno', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TURNO_PROXIMO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'TURNO_PROXIMO'), 'CORREO', 'Se acerca tu turno', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('ACUERDO_EN_VOTACION_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'ACUERDO_EN_VOTACION'), 'IN_APP', 'Hay algo para votar', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('ACUERDO_EN_VOTACION_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'ACUERDO_EN_VOTACION'), 'PUSH', 'Hay algo para votar', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('ACUERDO_EN_VOTACION_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'ACUERDO_EN_VOTACION'), 'CORREO', 'Hay algo para votar', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('INSIGNIA_OTORGADA_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'INSIGNIA_OTORGADA'), 'IN_APP', 'Ganaste una insignia', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('INSIGNIA_OTORGADA_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'INSIGNIA_OTORGADA'), 'PUSH', 'Ganaste una insignia', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('INSIGNIA_OTORGADA_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'INSIGNIA_OTORGADA'), 'CORREO', 'Ganaste una insignia', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TICKET_ACTUALIZADO_IN_APP', (SELECT id FROM evento_notificable WHERE tipo = 'TICKET_ACTUALIZADO'), 'IN_APP', 'Novedades en tu ticket', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TICKET_ACTUALIZADO_PUSH', (SELECT id FROM evento_notificable WHERE tipo = 'TICKET_ACTUALIZADO'), 'PUSH', 'Novedades en tu ticket', 'UTILITY', 'APROBADA', NULL, TRUE),
  ('TICKET_ACTUALIZADO_CORREO', (SELECT id FROM evento_notificable WHERE tipo = 'TICKET_ACTUALIZADO'), 'CORREO', 'Novedades en tu ticket', 'UTILITY', 'APROBADA', NULL, TRUE)
ON CONFLICT (codigo) DO NOTHING;

-- El texto es dato versionado: corregir una redacción es publicar la versión 2 y cerrar la 1, para que un envío viejo se pueda reproducir tal como salió.
INSERT INTO version_plantilla (plantilla_id, version, idioma, asunto, cuerpo, variables, botones, url_encabezado_media, vigente_desde, vigente_hasta) VALUES
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'OTP_SEGUNDO_FACTOR_WA'), 1, 'es-BO', NULL, '{{codigo}} es tu código de verificación de AportaYa. Vence en {{minutos}} minutos. No lo compartas con nadie: AportaYa nunca te lo va a pedir por teléfono ni por chat.', '{"codigo": "string", "minutos": "number"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'OTP_SEGUNDO_FACTOR_SMS'), 1, 'es-BO', NULL, 'AportaYa: {{codigo}} es tu codigo. Vence en {{minutos}} min. No lo compartas.', '{"codigo": "string", "minutos": "number"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'SEGURIDAD_SESION_NUEVA_PUSH'), 1, 'es-BO', 'Inicio de sesión nuevo', 'Se inició sesión en tu cuenta desde {{dispositivo}} ({{ciudad}}) el {{fecha_hora}}. Si no fuiste vos, bloqueá la cuenta desde la app ahora mismo.', '{"dispositivo": "string", "ciudad": "string", "fecha_hora": "datetime"}'::jsonb, '[{"tipo": "APP", "texto": "No fui yo", "ruta": "/seguridad/bloquear"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'SEGURIDAD_CUENTA_BLOQUEADA_WA'), 1, 'es-BO', NULL, 'Tu cuenta de AportaYa quedó bloqueada el {{fecha_hora}} por {{motivo}}. Tu saldo está intacto. Para desbloquearla, escribinos o entrá al Punto de Reclamo desde la app.', '{"fecha_hora": "datetime", "motivo": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TX_RECARGA_ACREDITADA_PUSH'), 1, 'es-BO', 'Saldo acreditado', 'Se acreditaron Bs {{monto}} en tu billetera. Saldo disponible: Bs {{saldo}}. Comprobante {{referencia}}.', '{"monto": "money", "saldo": "money", "referencia": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TX_APORTE_ACREDITADO_WA'), 1, 'es-BO', NULL, 'Listo, {{nombre}}. Tu aporte de Bs {{monto}} al grupo {{grupo}} ({{periodo}}) quedó acreditado el {{fecha_hora}}. Constancia: {{codigo_verificacion}}.', '{"nombre": "string", "monto": "money", "grupo": "string", "periodo": "string", "fecha_hora": "datetime", "codigo_verificacion": "string"}'::jsonb, '[{"tipo": "URL", "texto": "Ver constancia", "url": "{{url_constancia}}"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TX_APORTE_RECHAZADO_WA'), 1, 'es-BO', NULL, '{{nombre}}: tu pago de Bs {{monto}} al grupo {{grupo}} no se pudo procesar ({{motivo}}). No se te descontó nada. Podés reintentar hasta el {{fecha_limite}}.', '{"nombre": "string", "monto": "money", "grupo": "string", "motivo": "string", "fecha_limite": "date"}'::jsonb, '[{"tipo": "URL", "texto": "Reintentar pago", "url": "{{url_pago}}"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TX_ENTREGA_ACREDITADA_WA'), 1, 'es-BO', NULL, '{{nombre}}, cobraste tu turno del grupo {{grupo}}. Bolsa: Bs {{bruto}}. Deducciones: Bs {{deducciones}}. Acreditado: Bs {{neto}}. Detalle en la app.', '{"nombre": "string", "grupo": "string", "bruto": "money", "deducciones": "money", "neto": "money"}'::jsonb, '[{"tipo": "URL", "texto": "Ver detalle", "url": "{{url_entrega}}"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TX_RETIRO_FALLIDO_WA'), 1, 'es-BO', NULL, '{{nombre}}: el banco rechazó tu retiro de Bs {{monto}} ({{motivo}}). Los Bs {{monto}} ya volvieron a tu billetera. Revisá la cuenta de destino e intentá de nuevo.', '{"nombre": "string", "monto": "money", "motivo": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'COB_APORTE_POR_VENCER_WA'), 1, 'es-BO', NULL, '{{nombre}}, tu aporte de Bs {{monto}} al grupo {{grupo}} vence el {{fecha_vencimiento}}. Podés pagarlo desde la app en un toque.', '{"nombre": "string", "monto": "money", "grupo": "string", "fecha_vencimiento": "date"}'::jsonb, '[{"tipo": "URL", "texto": "Pagar ahora", "url": "{{url_pago}}"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'COB_APORTE_VENCIDO_WA'), 1, 'es-BO', NULL, '{{nombre}}: tu aporte al grupo {{grupo}} venció el {{fecha_vencimiento}}. Total a pagar hoy: Bs {{total}} (aporte Bs {{monto}} + recargo Bs {{mora}}). Si necesitás otro plazo, escribinos.', '{"nombre": "string", "grupo": "string", "fecha_vencimiento": "date", "total": "money", "monto": "money", "mora": "money"}'::jsonb, '[{"tipo": "URL", "texto": "Pagar ahora", "url": "{{url_pago}}"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'COB_COBERTURA_APLICADA_WA'), 1, 'es-BO', NULL, '{{nombre}}: el fondo de garantía del grupo {{grupo}} cubrió tu aporte de Bs {{monto}} para que el grupo no se frene. Queda una deuda a tu nombre por Bs {{deuda}}. Podés regularizarla o pedir un plan de pagos.', '{"nombre": "string", "grupo": "string", "monto": "money", "deuda": "money"}'::jsonb, '[{"tipo": "URL", "texto": "Regularizar", "url": "{{url_deuda}}"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'REG_RECLAMO_RECIBIDO_CORREO'), 1, 'es-BO', 'Recibimos tu reclamo {{codigo_reclamo}}', 'Estimado/a {{nombre}}:

Registramos tu reclamo con el código {{codigo_reclamo}} el {{fecha_recepcion}}.

Te vamos a responder a más tardar el {{fecha_limite}} ({{dias_habiles}} días hábiles). Si la respuesta no te conforma, podés recurrir a segunda instancia ante la Autoridad de Supervisión del Sistema Financiero (ASFI).

Punto de Reclamo AportaYa', '{"nombre": "string", "codigo_reclamo": "string", "fecha_recepcion": "date", "fecha_limite": "date", "dias_habiles": "number"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'REG_RECLAMO_RESUELTO_CORREO'), 1, 'es-BO', 'Respuesta a tu reclamo {{codigo_reclamo}}', 'Estimado/a {{nombre}}:

Sobre tu reclamo {{codigo_reclamo}}, la resolución es: {{resultado}}.

Fundamento: {{motivacion}}

{{detalle_reparacion}}

Si no estás de acuerdo, tenés {{dias_segunda_instancia}} días hábiles para recurrir a segunda instancia ante ASFI.

Punto de Reclamo AportaYa', '{"nombre": "string", "codigo_reclamo": "string", "resultado": "string", "motivacion": "string", "detalle_reparacion": "string", "dias_segunda_instancia": "number"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'REG_DESCARGO_HABILITADO_CORREO'), 1, 'es-BO', 'Tenés plazo para presentar descargo — {{codigo_registro}}', 'Estimado/a {{nombre}}:

Se registró un presunto incumplimiento ({{causal}}) en el grupo {{grupo}} el {{fecha_hecho}}.

Antes de resolver nada, tenés hasta el {{fecha_limite_descargo}} ({{dias_habiles}} días hábiles) para presentar tu descargo y adjuntar la evidencia que quieras.

Si no presentás descargo dentro del plazo, se resuelve con lo que hay en el expediente.

AportaYa', '{"nombre": "string", "codigo_registro": "string", "causal": "string", "grupo": "string", "fecha_hecho": "date", "fecha_limite_descargo": "date", "dias_habiles": "number"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'REG_TARIFARIO_MODIFICADO_CORREO'), 1, 'es-BO', 'Cambio de tarifario desde el {{vigente_desde}}', 'Estimado/a {{nombre}}:

A partir del {{vigente_desde}} rige el tarifario {{version_tarifario}}. Te avisamos con {{dias_preaviso}} días de anticipación, como corresponde.

Cambios: {{resumen_cambios}}

El tarifario completo está publicado en {{url_tarifario}}. Las operaciones anteriores al {{vigente_desde}} conservan la tarifa que tenían congelada.

AportaYa', '{"nombre": "string", "vigente_desde": "date", "version_tarifario": "string", "dias_preaviso": "number", "resumen_cambios": "string", "url_tarifario": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'GRP_SORTEO_REALIZADO_PUSH'), 1, 'es-BO', 'Ya salió el orden de turnos', 'El grupo {{grupo}} sorteó su orden de turnos. Te tocó el turno {{numero_turno}} de {{total_turnos}}. Podés verificar el sorteo con la semilla {{semilla}}.', '{"grupo": "string", "numero_turno": "number", "total_turnos": "number", "semilla": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Verificar sorteo", "ruta": "/grupos/{{grupo_id}}/sorteo"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'GRP_INVITACION_WA'), 1, 'es-BO', NULL, '{{invitante}} te invitó al pasanaku "{{grupo}}": Bs {{monto_aporte}} por {{periodicidad}}, {{cupos}} personas. El enlace es de un solo uso y vence el {{fecha_expira}}.', '{"invitante": "string", "grupo": "string", "monto_aporte": "money", "periodicidad": "string", "cupos": "number", "fecha_expira": "date"}'::jsonb, '[{"tipo": "URL", "texto": "Ver invitación", "url": "{{url_invitacion}}"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'INICIO_SESION_NUEVO_DISPOSITIVO_IN_APP'), 1, 'es-BO', 'Inicio de sesión desde un dispositivo nuevo', 'Se inició sesión en tu cuenta desde {{dispositivo}} ({{ciudad}}) el {{fecha_hora}}. Si no fuiste vos, bloqueá la cuenta ahora.', '{"dispositivo": "string", "ciudad": "string", "fecha_hora": "datetime"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/seguridad/dispositivos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'INICIO_SESION_NUEVO_DISPOSITIVO_CORREO'), 1, 'es-BO', 'Inicio de sesión desde un dispositivo nuevo', 'Se inició sesión en tu cuenta desde {{dispositivo}} ({{ciudad}}) el {{fecha_hora}}. Si no fuiste vos, bloqueá la cuenta ahora.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"dispositivo": "string", "ciudad": "string", "fecha_hora": "datetime"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'SEGUNDO_FACTOR_SOLICITADO_IN_APP'), 1, 'es-BO', 'Tu código de verificación', '{{codigo}} es tu código de verificación. Vence en {{minutos}} minutos. Nadie de AportaYa te lo va a pedir.', '{"codigo": "string", "minutos": "number"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/seguridad/verificacion"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'SEGUNDO_FACTOR_SOLICITADO_PUSH'), 1, 'es-BO', 'Tu código de verificación', '{{codigo}} es tu código de verificación. Vence en {{minutos}} minutos. Nadie de AportaYa te lo va a pedir.', '{"codigo": "string", "minutos": "number"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/seguridad/verificacion"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'SEGUNDO_FACTOR_SOLICITADO_CORREO'), 1, 'es-BO', 'Tu código de verificación', '{{codigo}} es tu código de verificación. Vence en {{minutos}} minutos. Nadie de AportaYa te lo va a pedir.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"codigo": "string", "minutos": "number"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CONTRASENA_CAMBIADA_IN_APP'), 1, 'es-BO', 'Tu contraseña cambió', 'Cambiaste la contraseña el {{fecha_hora}} desde {{dispositivo}}. Si no fuiste vos, recuperá el acceso ahora.', '{"fecha_hora": "datetime", "dispositivo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/seguridad/contrasena"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CONTRASENA_CAMBIADA_PUSH'), 1, 'es-BO', 'Tu contraseña cambió', 'Cambiaste la contraseña el {{fecha_hora}} desde {{dispositivo}}. Si no fuiste vos, recuperá el acceso ahora.', '{"fecha_hora": "datetime", "dispositivo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/seguridad/contrasena"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CONTRASENA_CAMBIADA_CORREO'), 1, 'es-BO', 'Tu contraseña cambió', 'Cambiaste la contraseña el {{fecha_hora}} desde {{dispositivo}}. Si no fuiste vos, recuperá el acceso ahora.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"fecha_hora": "datetime", "dispositivo": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TELEFONO_CAMBIADO_IN_APP'), 1, 'es-BO', 'Tu teléfono cambió', 'El teléfono de la cuenta cambió a {{telefono_enmascarado}} el {{fecha_hora}}. Si no fuiste vos, contactanos ya.', '{"telefono_enmascarado": "string", "fecha_hora": "datetime"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/seguridad/datos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TELEFONO_CAMBIADO_PUSH'), 1, 'es-BO', 'Tu teléfono cambió', 'El teléfono de la cuenta cambió a {{telefono_enmascarado}} el {{fecha_hora}}. Si no fuiste vos, contactanos ya.', '{"telefono_enmascarado": "string", "fecha_hora": "datetime"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/seguridad/datos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TELEFONO_CAMBIADO_CORREO'), 1, 'es-BO', 'Tu teléfono cambió', 'El teléfono de la cuenta cambió a {{telefono_enmascarado}} el {{fecha_hora}}. Si no fuiste vos, contactanos ya.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"telefono_enmascarado": "string", "fecha_hora": "datetime"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'DISPOSITIVO_AUTORIZADO_IN_APP'), 1, 'es-BO', 'Nuevo dispositivo de confianza', 'Autorizaste {{dispositivo}} como dispositivo de confianza el {{fecha_hora}}.', '{"dispositivo": "string", "fecha_hora": "datetime"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/seguridad/dispositivos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'DISPOSITIVO_AUTORIZADO_PUSH'), 1, 'es-BO', 'Nuevo dispositivo de confianza', 'Autorizaste {{dispositivo}} como dispositivo de confianza el {{fecha_hora}}.', '{"dispositivo": "string", "fecha_hora": "datetime"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/seguridad/dispositivos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'DISPOSITIVO_AUTORIZADO_CORREO'), 1, 'es-BO', 'Nuevo dispositivo de confianza', 'Autorizaste {{dispositivo}} como dispositivo de confianza el {{fecha_hora}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"dispositivo": "string", "fecha_hora": "datetime"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CUENTA_BLOQUEADA_IN_APP'), 1, 'es-BO', 'Tu cuenta está bloqueada', 'Bloqueamos tu cuenta el {{fecha_hora}} por {{motivo}}. Tus fondos siguen intactos. Para desbloquearla, entrá a la app.', '{"fecha_hora": "datetime", "motivo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/seguridad/bloqueo"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CUENTA_BLOQUEADA_PUSH'), 1, 'es-BO', 'Tu cuenta está bloqueada', 'Bloqueamos tu cuenta el {{fecha_hora}} por {{motivo}}. Tus fondos siguen intactos. Para desbloquearla, entrá a la app.', '{"fecha_hora": "datetime", "motivo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/seguridad/bloqueo"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CUENTA_BLOQUEADA_CORREO'), 1, 'es-BO', 'Tu cuenta está bloqueada', 'Bloqueamos tu cuenta el {{fecha_hora}} por {{motivo}}. Tus fondos siguen intactos. Para desbloquearla, entrá a la app.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"fecha_hora": "datetime", "motivo": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RECARGA_ACREDITADA_IN_APP'), 1, 'es-BO', 'Recarga acreditada', 'Acreditamos {{monto}} en tu billetera. Saldo disponible: {{saldo}}. Comprobante {{comprobante}}.', '{"monto": "money", "saldo": "money", "comprobante": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/movimientos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RECARGA_ACREDITADA_CORREO'), 1, 'es-BO', 'Recarga acreditada', 'Acreditamos {{monto}} en tu billetera. Saldo disponible: {{saldo}}. Comprobante {{comprobante}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "saldo": "money", "comprobante": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_ACREDITADO_IN_APP'), 1, 'es-BO', 'Aporte registrado', 'Registramos tu aporte de {{monto}} al grupo {{grupo}}, período {{periodo}}. Comprobante {{comprobante}}.', '{"monto": "money", "grupo": "string", "periodo": "string", "comprobante": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/aportes"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_ACREDITADO_PUSH'), 1, 'es-BO', 'Aporte registrado', 'Registramos tu aporte de {{monto}} al grupo {{grupo}}, período {{periodo}}. Comprobante {{comprobante}}.', '{"monto": "money", "grupo": "string", "periodo": "string", "comprobante": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/aportes"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_ACREDITADO_CORREO'), 1, 'es-BO', 'Aporte registrado', 'Registramos tu aporte de {{monto}} al grupo {{grupo}}, período {{periodo}}. Comprobante {{comprobante}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "grupo": "string", "periodo": "string", "comprobante": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_RECHAZADO_IN_APP'), 1, 'es-BO', 'No pudimos registrar tu aporte', 'Tu aporte de {{monto}} al grupo {{grupo}} no se pudo registrar: {{motivo}}. No se descontó nada de tu saldo.', '{"monto": "money", "grupo": "string", "motivo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/aportes"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_RECHAZADO_PUSH'), 1, 'es-BO', 'No pudimos registrar tu aporte', 'Tu aporte de {{monto}} al grupo {{grupo}} no se pudo registrar: {{motivo}}. No se descontó nada de tu saldo.', '{"monto": "money", "grupo": "string", "motivo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/aportes"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_RECHAZADO_CORREO'), 1, 'es-BO', 'No pudimos registrar tu aporte', 'Tu aporte de {{monto}} al grupo {{grupo}} no se pudo registrar: {{motivo}}. No se descontó nada de tu saldo.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "grupo": "string", "motivo": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TRANSFERENCIA_RECIBIDA_IN_APP'), 1, 'es-BO', 'Recibiste una transferencia', 'Recibiste {{monto}} de {{origen}}. Saldo disponible: {{saldo}}.', '{"monto": "money", "origen": "string", "saldo": "money"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/movimientos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TRANSFERENCIA_RECIBIDA_PUSH'), 1, 'es-BO', 'Recibiste una transferencia', 'Recibiste {{monto}} de {{origen}}. Saldo disponible: {{saldo}}.', '{"monto": "money", "origen": "string", "saldo": "money"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/movimientos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TRANSFERENCIA_RECIBIDA_CORREO'), 1, 'es-BO', 'Recibiste una transferencia', 'Recibiste {{monto}} de {{origen}}. Saldo disponible: {{saldo}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "origen": "string", "saldo": "money"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RETIRO_EJECUTADO_IN_APP'), 1, 'es-BO', 'Retiro enviado', 'Enviamos {{monto}} a tu cuenta {{cuenta_enmascarada}}. Orden {{orden}}. Puede tardar hasta {{plazo}} en acreditarse.', '{"monto": "money", "cuenta_enmascarada": "string", "orden": "string", "plazo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/retiros"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RETIRO_EJECUTADO_PUSH'), 1, 'es-BO', 'Retiro enviado', 'Enviamos {{monto}} a tu cuenta {{cuenta_enmascarada}}. Orden {{orden}}. Puede tardar hasta {{plazo}} en acreditarse.', '{"monto": "money", "cuenta_enmascarada": "string", "orden": "string", "plazo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/retiros"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RETIRO_EJECUTADO_CORREO'), 1, 'es-BO', 'Retiro enviado', 'Enviamos {{monto}} a tu cuenta {{cuenta_enmascarada}}. Orden {{orden}}. Puede tardar hasta {{plazo}} en acreditarse.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "cuenta_enmascarada": "string", "orden": "string", "plazo": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RETIRO_FALLIDO_IN_APP'), 1, 'es-BO', 'Tu retiro no se pudo completar', 'El retiro de {{monto}} falló: {{motivo}}. Te devolvimos el dinero a tu billetera.', '{"monto": "money", "motivo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/retiros"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RETIRO_FALLIDO_PUSH'), 1, 'es-BO', 'Tu retiro no se pudo completar', 'El retiro de {{monto}} falló: {{motivo}}. Te devolvimos el dinero a tu billetera.', '{"monto": "money", "motivo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/retiros"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RETIRO_FALLIDO_CORREO'), 1, 'es-BO', 'Tu retiro no se pudo completar', 'El retiro de {{monto}} falló: {{motivo}}. Te devolvimos el dinero a tu billetera.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "motivo": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'ENTREGA_ACREDITADA_IN_APP'), 1, 'es-BO', '¡Te tocó la bolsa!', 'Acreditamos {{monto}} del grupo {{grupo}}, turno {{turno}}. Saldo disponible: {{saldo}}.', '{"monto": "money", "grupo": "string", "turno": "number", "saldo": "money"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/entregas"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'ENTREGA_ACREDITADA_PUSH'), 1, 'es-BO', '¡Te tocó la bolsa!', 'Acreditamos {{monto}} del grupo {{grupo}}, turno {{turno}}. Saldo disponible: {{saldo}}.', '{"monto": "money", "grupo": "string", "turno": "number", "saldo": "money"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/entregas"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'ENTREGA_ACREDITADA_CORREO'), 1, 'es-BO', '¡Te tocó la bolsa!', 'Acreditamos {{monto}} del grupo {{grupo}}, turno {{turno}}. Saldo disponible: {{saldo}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "grupo": "string", "turno": "number", "saldo": "money"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'REVERSO_APLICADO_IN_APP'), 1, 'es-BO', 'Reversamos una operación', 'Reversamos {{monto}} de la operación {{operacion}} del {{fecha}}: {{motivo}}. Saldo disponible: {{saldo}}.', '{"monto": "money", "operacion": "string", "fecha": "date", "motivo": "string", "saldo": "money"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/movimientos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'REVERSO_APLICADO_PUSH'), 1, 'es-BO', 'Reversamos una operación', 'Reversamos {{monto}} de la operación {{operacion}} del {{fecha}}: {{motivo}}. Saldo disponible: {{saldo}}.', '{"monto": "money", "operacion": "string", "fecha": "date", "motivo": "string", "saldo": "money"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/movimientos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'REVERSO_APLICADO_CORREO'), 1, 'es-BO', 'Reversamos una operación', 'Reversamos {{monto}} de la operación {{operacion}} del {{fecha}}: {{motivo}}. Saldo disponible: {{saldo}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "operacion": "string", "fecha": "date", "motivo": "string", "saldo": "money"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'COMISION_COBRADA_IN_APP'), 1, 'es-BO', 'Comisión cobrada', 'Cobramos {{monto}} por {{concepto}}. Detalle en tu extracto.', '{"monto": "money", "concepto": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/movimientos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'COMISION_COBRADA_PUSH'), 1, 'es-BO', 'Comisión cobrada', 'Cobramos {{monto}} por {{concepto}}. Detalle en tu extracto.', '{"monto": "money", "concepto": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/movimientos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'COMISION_COBRADA_CORREO'), 1, 'es-BO', 'Comisión cobrada', 'Cobramos {{monto}} por {{concepto}}. Detalle en tu extracto.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "concepto": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'FACTURA_EMITIDA_IN_APP'), 1, 'es-BO', 'Tu factura está lista', 'Emitimos la factura {{numero}} por {{monto}} del {{fecha}}. La podés descargar desde la app.', '{"numero": "string", "monto": "money", "fecha": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/facturas"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'FACTURA_EMITIDA_PUSH'), 1, 'es-BO', 'Tu factura está lista', 'Emitimos la factura {{numero}} por {{monto}} del {{fecha}}. La podés descargar desde la app.', '{"numero": "string", "monto": "money", "fecha": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/billetera/facturas"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'FACTURA_EMITIDA_CORREO'), 1, 'es-BO', 'Tu factura está lista', 'Emitimos la factura {{numero}} por {{monto}} del {{fecha}}. La podés descargar desde la app.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"numero": "string", "monto": "money", "fecha": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_POR_VENCER_IN_APP'), 1, 'es-BO', 'Tu aporte vence pronto', 'El aporte de {{monto}} al grupo {{grupo}} vence el {{fecha_limite}}. Podés pagarlo desde la app.', '{"monto": "money", "grupo": "string", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/aportes"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_POR_VENCER_PUSH'), 1, 'es-BO', 'Tu aporte vence pronto', 'El aporte de {{monto}} al grupo {{grupo}} vence el {{fecha_limite}}. Podés pagarlo desde la app.', '{"monto": "money", "grupo": "string", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/aportes"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_POR_VENCER_CORREO'), 1, 'es-BO', 'Tu aporte vence pronto', 'El aporte de {{monto}} al grupo {{grupo}} vence el {{fecha_limite}}. Podés pagarlo desde la app.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "grupo": "string", "fecha_limite": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_VENCIDO_IN_APP'), 1, 'es-BO', 'Tu aporte está vencido', 'El aporte de {{monto}} al grupo {{grupo}} venció el {{fecha_limite}}. Regularizalo para evitar mora.', '{"monto": "money", "grupo": "string", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/aportes"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_VENCIDO_PUSH'), 1, 'es-BO', 'Tu aporte está vencido', 'El aporte de {{monto}} al grupo {{grupo}} venció el {{fecha_limite}}. Regularizalo para evitar mora.', '{"monto": "money", "grupo": "string", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/aportes"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'APORTE_VENCIDO_CORREO'), 1, 'es-BO', 'Tu aporte está vencido', 'El aporte de {{monto}} al grupo {{grupo}} venció el {{fecha_limite}}. Regularizalo para evitar mora.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "grupo": "string", "fecha_limite": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'MORA_APLICADA_IN_APP'), 1, 'es-BO', 'Se aplicó mora a tu aporte', 'Aplicamos {{monto_mora}} de mora sobre el aporte vencido del grupo {{grupo}}. Deuda total: {{deuda}}.', '{"monto_mora": "money", "grupo": "string", "deuda": "money"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/aportes"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'MORA_APLICADA_PUSH'), 1, 'es-BO', 'Se aplicó mora a tu aporte', 'Aplicamos {{monto_mora}} de mora sobre el aporte vencido del grupo {{grupo}}. Deuda total: {{deuda}}.', '{"monto_mora": "money", "grupo": "string", "deuda": "money"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/aportes"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'MORA_APLICADA_CORREO'), 1, 'es-BO', 'Se aplicó mora a tu aporte', 'Aplicamos {{monto_mora}} de mora sobre el aporte vencido del grupo {{grupo}}. Deuda total: {{deuda}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto_mora": "money", "grupo": "string", "deuda": "money"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'COBERTURA_APLICADA_IN_APP'), 1, 'es-BO', 'El fondo de garantía cubrió tu aporte', 'El fondo de garantía cubrió {{monto}} de tu aporte al grupo {{grupo}}. Quedás con una deuda de {{deuda}} a regularizar hasta el {{fecha_limite}}.', '{"monto": "money", "grupo": "string", "deuda": "money", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/deuda"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'COBERTURA_APLICADA_PUSH'), 1, 'es-BO', 'El fondo de garantía cubrió tu aporte', 'El fondo de garantía cubrió {{monto}} de tu aporte al grupo {{grupo}}. Quedás con una deuda de {{deuda}} a regularizar hasta el…', '{"monto": "money", "grupo": "string", "deuda": "money", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/deuda"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'COBERTURA_APLICADA_CORREO'), 1, 'es-BO', 'El fondo de garantía cubrió tu aporte', 'El fondo de garantía cubrió {{monto}} de tu aporte al grupo {{grupo}}. Quedás con una deuda de {{deuda}} a regularizar hasta el {{fecha_limite}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "grupo": "string", "deuda": "money", "fecha_limite": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'PROMESA_DE_PAGO_POR_VENCER_IN_APP'), 1, 'es-BO', 'Tu promesa de pago vence pronto', 'Te comprometiste a pagar {{monto}} hasta el {{fecha_limite}}. Faltan {{dias}} días.', '{"monto": "money", "fecha_limite": "date", "dias": "number"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/deuda"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'PROMESA_DE_PAGO_POR_VENCER_PUSH'), 1, 'es-BO', 'Tu promesa de pago vence pronto', 'Te comprometiste a pagar {{monto}} hasta el {{fecha_limite}}. Faltan {{dias}} días.', '{"monto": "money", "fecha_limite": "date", "dias": "number"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/deuda"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'PROMESA_DE_PAGO_POR_VENCER_CORREO'), 1, 'es-BO', 'Tu promesa de pago vence pronto', 'Te comprometiste a pagar {{monto}} hasta el {{fecha_limite}}. Faltan {{dias}} días.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"monto": "money", "fecha_limite": "date", "dias": "number"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'PLAN_REGULARIZACION_APROBADO_IN_APP'), 1, 'es-BO', 'Aprobamos tu plan de regularización', 'Tu plan de {{cuotas}} cuotas de {{monto_cuota}} quedó aprobado. La primera vence el {{fecha_primera}}.', '{"cuotas": "number", "monto_cuota": "money", "fecha_primera": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/deuda"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'PLAN_REGULARIZACION_APROBADO_PUSH'), 1, 'es-BO', 'Aprobamos tu plan de regularización', 'Tu plan de {{cuotas}} cuotas de {{monto_cuota}} quedó aprobado. La primera vence el {{fecha_primera}}.', '{"cuotas": "number", "monto_cuota": "money", "fecha_primera": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/deuda"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'PLAN_REGULARIZACION_APROBADO_CORREO'), 1, 'es-BO', 'Aprobamos tu plan de regularización', 'Tu plan de {{cuotas}} cuotas de {{monto_cuota}} quedó aprobado. La primera vence el {{fecha_primera}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"cuotas": "number", "monto_cuota": "money", "fecha_primera": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RECLAMO_RECIBIDO_IN_APP'), 1, 'es-BO', 'Recibimos tu reclamo', 'Registramos tu reclamo {{codigo}} el {{fecha}}. Tenemos plazo hasta el {{fecha_limite}} para responderte.', '{"codigo": "string", "fecha": "date", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/reclamos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RECLAMO_RECIBIDO_PUSH'), 1, 'es-BO', 'Recibimos tu reclamo', 'Registramos tu reclamo {{codigo}} el {{fecha}}. Tenemos plazo hasta el {{fecha_limite}} para responderte.', '{"codigo": "string", "fecha": "date", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/reclamos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RECLAMO_RESUELTO_IN_APP'), 1, 'es-BO', 'Resolvimos tu reclamo', 'El reclamo {{codigo}} quedó resuelto: {{resultado}}. Si no estás de acuerdo, podés acudir a la ASFI.', '{"codigo": "string", "resultado": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/reclamos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'RECLAMO_RESUELTO_PUSH'), 1, 'es-BO', 'Resolvimos tu reclamo', 'El reclamo {{codigo}} quedó resuelto: {{resultado}}. Si no estás de acuerdo, podés acudir a la ASFI.', '{"codigo": "string", "resultado": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/reclamos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TARIFARIO_MODIFICADO_IN_APP'), 1, 'es-BO', 'Cambian nuestras comisiones', 'Desde el {{vigente_desde}} rige un tarifario nuevo. Los cambios están detallados en la app y en nuestro sitio.', '{"vigente_desde": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/legal/tarifario"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TARIFARIO_MODIFICADO_PUSH'), 1, 'es-BO', 'Cambian nuestras comisiones', 'Desde el {{vigente_desde}} rige un tarifario nuevo. Los cambios están detallados en la app y en nuestro sitio.', '{"vigente_desde": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/legal/tarifario"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CONTRATO_MODIFICADO_IN_APP'), 1, 'es-BO', 'Cambia el contrato de la billetera', 'Desde el {{vigente_desde}} rige la versión {{version}} del contrato. Podés leerla y aceptarla en la app.', '{"vigente_desde": "date", "version": "number"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/legal/contrato"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CONTRATO_MODIFICADO_PUSH'), 1, 'es-BO', 'Cambia el contrato de la billetera', 'Desde el {{vigente_desde}} rige la versión {{version}} del contrato. Podés leerla y aceptarla en la app.', '{"vigente_desde": "date", "version": "number"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/legal/contrato"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CONTRATO_MODIFICADO_CORREO'), 1, 'es-BO', 'Cambia el contrato de la billetera', 'Desde el {{vigente_desde}} rige la versión {{version}} del contrato. Podés leerla y aceptarla en la app.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"vigente_desde": "date", "version": "number"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'REVISION_KYC_REQUERIDA_IN_APP'), 1, 'es-BO', 'Necesitamos actualizar tus datos', 'Tenés que actualizar tus datos de identidad antes del {{fecha_limite}} para seguir operando sin límites.', '{"fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/perfil/identidad"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'REVISION_KYC_REQUERIDA_PUSH'), 1, 'es-BO', 'Necesitamos actualizar tus datos', 'Tenés que actualizar tus datos de identidad antes del {{fecha_limite}} para seguir operando sin límites.', '{"fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/perfil/identidad"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'REVISION_KYC_REQUERIDA_CORREO'), 1, 'es-BO', 'Necesitamos actualizar tus datos', 'Tenés que actualizar tus datos de identidad antes del {{fecha_limite}} para seguir operando sin límites.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"fecha_limite": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CUENTA_RESTRINGIDA_CUMPLIMIENTO_IN_APP'), 1, 'es-BO', 'Tu cuenta quedó restringida', 'Restringimos tu cuenta el {{fecha}} por {{motivo}}. Podés presentar tu descargo hasta el {{fecha_limite}}.', '{"fecha": "date", "motivo": "string", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/descargo"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CUENTA_RESTRINGIDA_CUMPLIMIENTO_PUSH'), 1, 'es-BO', 'Tu cuenta quedó restringida', 'Restringimos tu cuenta el {{fecha}} por {{motivo}}. Podés presentar tu descargo hasta el {{fecha_limite}}.', '{"fecha": "date", "motivo": "string", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/descargo"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'CUENTA_RESTRINGIDA_CUMPLIMIENTO_CORREO'), 1, 'es-BO', 'Tu cuenta quedó restringida', 'Restringimos tu cuenta el {{fecha}} por {{motivo}}. Podés presentar tu descargo hasta el {{fecha_limite}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"fecha": "date", "motivo": "string", "fecha_limite": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'DESCARGO_HABILITADO_IN_APP'), 1, 'es-BO', 'Podés presentar tu descargo', 'Tenés hasta el {{fecha_limite}} ({{dias_habiles}} días hábiles) para presentar tu descargo sobre {{asunto}}.', '{"fecha_limite": "date", "dias_habiles": "number", "asunto": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/descargo"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'DESCARGO_HABILITADO_PUSH'), 1, 'es-BO', 'Podés presentar tu descargo', 'Tenés hasta el {{fecha_limite}} ({{dias_habiles}} días hábiles) para presentar tu descargo sobre {{asunto}}.', '{"fecha_limite": "date", "dias_habiles": "number", "asunto": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/descargo"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'SANCION_NOTIFICADA_IN_APP'), 1, 'es-BO', 'Te notificamos una sanción', 'Aplicamos {{sancion}} por {{causal}}, con efecto desde el {{fecha}}. Podés apelar una sola vez hasta el {{fecha_limite}}.', '{"sancion": "string", "causal": "string", "fecha": "date", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/sanciones"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'SANCION_NOTIFICADA_PUSH'), 1, 'es-BO', 'Te notificamos una sanción', 'Aplicamos {{sancion}} por {{causal}}, con efecto desde el {{fecha}}. Podés apelar una sola vez hasta el {{fecha_limite}}.', '{"sancion": "string", "causal": "string", "fecha": "date", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/sanciones"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'SANCION_NOTIFICADA_CORREO'), 1, 'es-BO', 'Te notificamos una sanción', 'Aplicamos {{sancion}} por {{causal}}, con efecto desde el {{fecha}}. Podés apelar una sola vez hasta el {{fecha_limite}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"sancion": "string", "causal": "string", "fecha": "date", "fecha_limite": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'INVITACION_A_GRUPO_IN_APP'), 1, 'es-BO', 'Te invitaron a un pasanaku', '{{invitante}} te invitó al grupo {{grupo}}: {{monto}} por período, {{cupos}} cupos. La invitación vence el {{fecha_limite}}.', '{"invitante": "string", "grupo": "string", "monto": "money", "cupos": "number", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/invitaciones"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'INVITACION_A_GRUPO_PUSH'), 1, 'es-BO', 'Te invitaron a un pasanaku', '{{invitante}} te invitó al grupo {{grupo}}: {{monto}} por período, {{cupos}} cupos. La invitación vence el {{fecha_limite}}.', '{"invitante": "string", "grupo": "string", "monto": "money", "cupos": "number", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/invitaciones"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'INVITACION_A_GRUPO_CORREO'), 1, 'es-BO', 'Te invitaron a un pasanaku', '{{invitante}} te invitó al grupo {{grupo}}: {{monto}} por período, {{cupos}} cupos. La invitación vence el {{fecha_limite}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"invitante": "string", "grupo": "string", "monto": "money", "cupos": "number", "fecha_limite": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'GRUPO_COMPLETO_IN_APP'), 1, 'es-BO', 'El grupo se completó', 'El grupo {{grupo}} llenó sus {{cupos}} cupos. El sorteo de turnos es el {{fecha_sorteo}}.', '{"grupo": "string", "cupos": "number", "fecha_sorteo": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'GRUPO_COMPLETO_PUSH'), 1, 'es-BO', 'El grupo se completó', 'El grupo {{grupo}} llenó sus {{cupos}} cupos. El sorteo de turnos es el {{fecha_sorteo}}.', '{"grupo": "string", "cupos": "number", "fecha_sorteo": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'GRUPO_COMPLETO_CORREO'), 1, 'es-BO', 'El grupo se completó', 'El grupo {{grupo}} llenó sus {{cupos}} cupos. El sorteo de turnos es el {{fecha_sorteo}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"grupo": "string", "cupos": "number", "fecha_sorteo": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'SORTEO_REALIZADO_IN_APP'), 1, 'es-BO', 'Ya hay turnos', 'Se sortearon los turnos del grupo {{grupo}}. Te tocó el turno {{turno}} de {{total}}, el {{fecha_turno}}.', '{"grupo": "string", "turno": "number", "total": "number", "fecha_turno": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/turnos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'SORTEO_REALIZADO_CORREO'), 1, 'es-BO', 'Ya hay turnos', 'Se sortearon los turnos del grupo {{grupo}}. Te tocó el turno {{turno}} de {{total}}, el {{fecha_turno}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"grupo": "string", "turno": "number", "total": "number", "fecha_turno": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TURNO_PROXIMO_IN_APP'), 1, 'es-BO', 'Se acerca tu turno', 'Tu turno en el grupo {{grupo}} es el {{fecha_turno}}. Vas a recibir {{monto}}.', '{"grupo": "string", "fecha_turno": "date", "monto": "money"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/turnos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TURNO_PROXIMO_PUSH'), 1, 'es-BO', 'Se acerca tu turno', 'Tu turno en el grupo {{grupo}} es el {{fecha_turno}}. Vas a recibir {{monto}}.', '{"grupo": "string", "fecha_turno": "date", "monto": "money"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/turnos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TURNO_PROXIMO_CORREO'), 1, 'es-BO', 'Se acerca tu turno', 'Tu turno en el grupo {{grupo}} es el {{fecha_turno}}. Vas a recibir {{monto}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"grupo": "string", "fecha_turno": "date", "monto": "money"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'ACUERDO_EN_VOTACION_IN_APP'), 1, 'es-BO', 'Hay algo para votar', 'El grupo {{grupo}} vota {{asunto}} hasta el {{fecha_limite}}. Tu voto cuenta.', '{"grupo": "string", "asunto": "string", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/acuerdos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'ACUERDO_EN_VOTACION_PUSH'), 1, 'es-BO', 'Hay algo para votar', 'El grupo {{grupo}} vota {{asunto}} hasta el {{fecha_limite}}. Tu voto cuenta.', '{"grupo": "string", "asunto": "string", "fecha_limite": "date"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/grupos/acuerdos"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'ACUERDO_EN_VOTACION_CORREO'), 1, 'es-BO', 'Hay algo para votar', 'El grupo {{grupo}} vota {{asunto}} hasta el {{fecha_limite}}. Tu voto cuenta.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"grupo": "string", "asunto": "string", "fecha_limite": "date"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'INSIGNIA_OTORGADA_IN_APP'), 1, 'es-BO', 'Ganaste una insignia', 'Te ganaste la insignia {{insignia}} por {{motivo}}.', '{"insignia": "string", "motivo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/perfil/reputacion"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'INSIGNIA_OTORGADA_PUSH'), 1, 'es-BO', 'Ganaste una insignia', 'Te ganaste la insignia {{insignia}} por {{motivo}}.', '{"insignia": "string", "motivo": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/perfil/reputacion"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'INSIGNIA_OTORGADA_CORREO'), 1, 'es-BO', 'Ganaste una insignia', 'Te ganaste la insignia {{insignia}} por {{motivo}}.

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"insignia": "string", "motivo": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TICKET_ACTUALIZADO_IN_APP'), 1, 'es-BO', 'Novedades en tu ticket', 'Tu ticket {{codigo}} pasó a {{estado}}. {{detalle}}', '{"codigo": "string", "estado": "string", "detalle": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/tickets"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TICKET_ACTUALIZADO_PUSH'), 1, 'es-BO', 'Novedades en tu ticket', 'Tu ticket {{codigo}} pasó a {{estado}}. {{detalle}}', '{"codigo": "string", "estado": "string", "detalle": "string"}'::jsonb, '[{"tipo": "APP", "texto": "Ver en la app", "ruta": "/soporte/tickets"}]'::jsonb, NULL, '2026-01-01T00:00:00-04:00', NULL),
  ((SELECT id FROM plantilla_mensaje WHERE codigo = 'TICKET_ACTUALIZADO_CORREO'), 1, 'es-BO', 'Novedades en tu ticket', 'Tu ticket {{codigo}} pasó a {{estado}}. {{detalle}}

AportaYa · Este es un mensaje automático; no respondas a esta dirección.', '{"codigo": "string", "estado": "string", "detalle": "string"}'::jsonb, NULL, NULL, '2026-01-01T00:00:00-04:00', NULL)
ON CONFLICT (plantilla_id, idioma, version) DO NOTHING;
