-- Grupo de pasanaku demo a mitad de camino: 6 cupos, Bs 500 mensuales, 6 períodos. El período 1 ya se cobró y se entregó; el período 2 venció con cinco pagos y un moroso.
-- GENERADO desde seeders/dev/03-grupo-demo.json — no editar a mano.

INSERT INTO organizador (usuario_id, estado, nivel, limite_grupos_simultaneos, limite_monto_administrado, grupos_activos, grupos_historicos, monto_administrado_actual, calificacion_promedio, indice_morosidad_cartera, fecha_postulacion, fecha_habilitacion) VALUES
  ((SELECT id FROM usuario WHERE codigo_publico = 'USR000001'), 'HABILITADO', 'ESTANDAR', 3, 50000, 1, 0, 3000, 0, 16.67, (current_date + interval '-120 days'), (current_date + interval '-60 days'))
ON CONFLICT DO NOTHING;

-- Sin capacitación vigente no hay habilitación: los dos módulos del nivel ESTANDAR (archivo mínimo 17, HAB_ESTANDAR_CAPACITACION).
INSERT INTO capacitacion_organizador (organizador_id, modulo, completada_en, puntaje_evaluacion, aprobada, vigente_hasta) VALUES
  ((SELECT id FROM organizador WHERE usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000001')), 'Reglas del pasanaku y responsabilidades del organizador', now() - interval '70 days', 92.0, TRUE, (current_date + interval '295 days')),
  ((SELECT id FROM organizador WHERE usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000001')), 'Manejo de mora, cobranza y trato al participante', now() - interval '68 days', 88.0, TRUE, (current_date + interval '297 days'))
ON CONFLICT DO NOTHING;

-- Token de firma consumido. La restricción ck_contrato_org_firma exige que un contrato firmado apunte al token con el que se firmó: la firma tiene que poder probarse.
INSERT INTO token_verificacion (usuario_id, politica_id, tipo_token, proposito, hash_token, algoritmo_hash, canal_entrega, destino_enmascarado, estado, emitido_en, expira_en, enviado_en, consumido_en, intentos_fallidos, max_intentos, reenvios, ip_origen, agente_usuario, correlation_id, clave_idempotencia, uso_unico, url_destino) VALUES
  ((SELECT id FROM usuario WHERE codigo_publico = 'USR000001'), (SELECT id FROM politica_token WHERE proposito = 'FIRMA_REGLAMENTO' ORDER BY vigente_desde DESC LIMIT 1), 'ENLACE', 'FIRMA_REGLAMENTO', encode(digest('demo-firma-contrato-organizador', 'sha256'), 'hex'), 'SHA-256', 'CORREO', 'd***1@pasanaku.test', 'CONSUMIDO', now() - interval '60 days', now() - interval '57 days', now() - interval '60 days', now() - interval '60 days', 0, 5, 0, '190.129.0.11', 'AportaYa/1.0 (Android 14)', gen_random_uuid(), 'demo-token-firma-contrato-org-001', TRUE, 'https://pasanaku.bo/firma/contrato-organizador')
ON CONFLICT DO NOTHING;

-- R-ORG-02: sin este contrato firmado y vigente, fn_org_validar_contrato_grupo() rechaza la creación del grupo. Es la primera restricción que se topa quien intente sembrar un grupo sin habilitar al organizador.
INSERT INTO contrato_organizador (organizador_id, version, contenido_hash, obligaciones, causales_rescision, firmado_en, token_firma_id, vigente_desde, vigente_hasta, rescindido_en, motivo_rescision) VALUES
  ((SELECT id FROM organizador WHERE usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000001')), 'v1', encode(digest('contrato-organizador-v1-demo', 'sha256'), 'hex'), 'Administrar el grupo sin custodiar dinero ni cobrar por fuera de la plataforma; convocar y registrar las decisiones del grupo; gestionar la mora dentro de la estrategia de cobranza vigente; no ocupar más de un cupo propio.', 'Cobro de dinero por fuera de la plataforma; sanción firme por incumplimiento del organizador; índice de morosidad de cartera superior al umbral por dos períodos consecutivos; inactividad mayor a 180 días.', now() - interval '60 days', (SELECT id FROM token_verificacion WHERE clave_idempotencia = 'demo-token-firma-contrato-org-001'), (current_date + interval '-60 days'), NULL, NULL, NULL)
ON CONFLICT DO NOTHING;

INSERT INTO grupo (codigo_publico, nombre, moneda, periodicidad, dia_cobro, num_periodos, cupos_totales, cupos_ocupados, monto_aporte, fecha_inicio, fecha_fin_estimada, estado, tipo_conformacion, modalidad_turnos, visibilidad, requiere_kyc_minimo, reputacion_minima, dias_gracia, porcentaje_fondo_garantia, quorum_decisiones, organizador_id, es_autogestionado, aplica_recargo_mora, usa_fondo_garantia) VALUES
  ('GRP-DEMO-01', 'Pasanaku demo del barrio', 'BOB', 'MENSUAL', 10, 6, 6, 6, 500.0, (current_date + interval '-45 days'), (current_date + interval '135 days'), 'EN_CURSO', 'MANUAL_POR_INVITACION', 'SORTEO_ALEATORIO', 'PRIVADO', 'BASICO', 0, 3, 5.0, 0.667, (SELECT id FROM organizador WHERE usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000001')), FALSE, TRUE, TRUE)
ON CONFLICT (codigo_publico) DO NOTHING;

-- Los booleanos van explícitos y no por omisión: este grupo aplica recargo por mora y usa fondo de garantía, permite hasta 2 cupos por persona y permuta de turnos, y no admite ingresos con el ciclo empezado.
INSERT INTO configuracion_grupo (grupo_id, max_cupos_por_persona, hora_limite_pago, tolerancia_monto_parcial, politica_mora_id, permite_cupos_multiples, permite_permuta_turnos, requiere_avalista, permite_ingreso_tardio) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 2, '20:00:00', 50.0, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1), TRUE, TRUE, FALSE, FALSE)
ON CONFLICT DO NOTHING;

INSERT INTO reglamento_grupo (grupo_id, version, contenido, hash_contenido, clausulas_mora, clausulas_abandono, vigente_desde, redactado_por) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 1, 'Reglamento del grupo demo. Aporte mensual de Bs 500 con vencimiento el día 10. Tres días de gracia. Recargo del 2 % sobre el aporte, con tope del 100 %. El fondo de garantía se constituye con Bs 100 por participante al inicio y cubre el aporte impago a partir del quinto día de mora, generando una deuda a nombre de quien no pagó. El orden de turnos se define por sorteo con semilla verificable.', encode(digest('reglamento-grupo-demo-v1', 'sha256'), 'hex'), 'Recargo del 2 % sobre el aporte impago, con tope del 100 % del aporte. La gracia es de 3 días corridos desde el vencimiento.', 'El cupo se libera y se busca reemplazo. La deuda no se extingue con la salida del grupo.', now() - interval '45 days', (SELECT id FROM usuario WHERE codigo_publico = 'USR000001'))
ON CONFLICT DO NOTHING;

-- El precio pactado no cambia a mitad del juego (R-TAR-07)
INSERT INTO tarifa_congelada_grupo (grupo_id, tarifario_id, snapshot_conceptos, hash_snapshot, congelada_en, vigente_hasta_ciclo_nro) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM tarifario WHERE codigo = 'GENERAL' AND version = 1), '{"COM_ENTREGA": {"metodo": "PORCENTUAL", "valor": 0.35, "piso": 10, "techo": 50, "tramo": "0 a 3000"}}'::jsonb, encode(digest('tarifa-congelada-grupo-demo-v1', 'sha256'), 'hex'), now() - interval '45 days', 6)
ON CONFLICT (grupo_id) DO NOTHING;

-- USR000004 está EN_MORA: es el caso que ejercita mora, cobertura del fondo, deuda y debido proceso.
INSERT INTO participante (grupo_id, usuario_id, alias, estado, reputacion_al_ingresar, aportes_realizados, aportes_en_mora, fecha_ingreso, es_organizador) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM usuario WHERE codigo_publico = 'USR000001'), 'María', 'ACTIVO', 700, 2, 0, now() - interval '45 days', TRUE),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM usuario WHERE codigo_publico = 'USR000002'), 'Juan', 'ACTIVO', 700, 2, 0, now() - interval '45 days', FALSE),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM usuario WHERE codigo_publico = 'USR000003'), 'Ana', 'ACTIVO', 700, 2, 0, now() - interval '45 days', FALSE),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM usuario WHERE codigo_publico = 'USR000004'), 'Pedro', 'EN_MORA', 700, 1, 1, now() - interval '45 days', FALSE),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM usuario WHERE codigo_publico = 'USR000005'), 'Rosa', 'ACTIVO', 700, 2, 0, now() - interval '45 days', FALSE),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM usuario WHERE codigo_publico = 'USR000006'), 'Luis', 'ACTIVO', 700, 2, 0, now() - interval '45 days', FALSE)
ON CONFLICT DO NOTHING;

INSERT INTO cupo (grupo_id, numero, estado, fraccion, asignado_en, participante_id) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 1, 'OCUPADO', 1.0, now() - interval '45 days', (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000001'))),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 2, 'OCUPADO', 1.0, now() - interval '45 days', (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000002'))),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 3, 'OCUPADO', 1.0, now() - interval '45 days', (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000003'))),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 4, 'OCUPADO', 1.0, now() - interval '45 days', (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000004'))),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 5, 'OCUPADO', 1.0, now() - interval '45 days', (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000005'))),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 6, 'OCUPADO', 1.0, now() - interval '45 days', (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000006')))
ON CONFLICT DO NOTHING;

-- Sorteo con compromiso y revelado: la semilla previa se publica antes, la del servidor después, y cualquiera puede recalcular el resultado (CU de transparencia).
INSERT INTO sorteo_turnos (grupo_id, algoritmo, estado, hash_semilla_previo, aportes_entropia, fecha_compromiso, fecha_revelado_prevista, semilla_servidor, semilla_publica, resultado, ejecutado_por, fecha_ejecucion) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'FISHER_YATES_HMAC', 'REVELADO', encode(digest('semilla-servidor-demo-grupo-01', 'sha256'), 'hex'), '{"participantes": ["USR000001", "USR000002", "USR000003", "USR000004", "USR000005", "USR000006"], "bloque_referencia": "cierre-2026-01"}'::jsonb, now() - interval '46 days', now() - interval '45 days', 'semilla-servidor-demo-grupo-01', 'entropia-publica-demo-grupo-01', '{"orden": [1, 2, 3, 4, 5, 6]}'::jsonb, (SELECT id FROM usuario WHERE codigo_publico = 'USR000001'), now() - interval '45 days')
ON CONFLICT DO NOTHING;

-- Los seis firmaron el reglamento antes de que arrancara el primer período: sin firma, la obligación no es oponible.
INSERT INTO aceptacion_reglamento (reglamento_id, participante_id, aceptado_en, hash_firmado, ip_origen) VALUES
  ((SELECT id FROM reglamento_grupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND version = 1), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000001')), now() - interval '45 days', encode(digest('reglamento-grupo-demo-v1', 'sha256'), 'hex'), '190.129.0.11'),
  ((SELECT id FROM reglamento_grupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND version = 1), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000002')), now() - interval '45 days', encode(digest('reglamento-grupo-demo-v1', 'sha256'), 'hex'), '190.129.0.12'),
  ((SELECT id FROM reglamento_grupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND version = 1), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000003')), now() - interval '45 days', encode(digest('reglamento-grupo-demo-v1', 'sha256'), 'hex'), '190.129.0.13'),
  ((SELECT id FROM reglamento_grupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND version = 1), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000004')), now() - interval '45 days', encode(digest('reglamento-grupo-demo-v1', 'sha256'), 'hex'), '190.129.0.14'),
  ((SELECT id FROM reglamento_grupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND version = 1), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000005')), now() - interval '45 days', encode(digest('reglamento-grupo-demo-v1', 'sha256'), 'hex'), '190.129.0.15'),
  ((SELECT id FROM reglamento_grupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND version = 1), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000006')), now() - interval '45 days', encode(digest('reglamento-grupo-demo-v1', 'sha256'), 'hex'), '190.129.0.16')
ON CONFLICT DO NOTHING;

-- Período 1 liquidado y entregado; período 2 vencido con un moroso; del 3 al 6 programados.
INSERT INTO periodo (grupo_id, numero, fecha_inicio, fecha_limite_pago, fecha_fin_gracia, fecha_entrega_prevista, estado, monto_objetivo, monto_recaudado, cupos_morosos) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 1, (current_date + interval '-45 days'), (current_date + interval '-35 days'), (current_date + interval '-32 days'), (current_date + interval '-30 days'), 'LIQUIDADO', 3000, 3000, 0),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 2, (current_date + interval '-15 days'), (current_date + interval '-8 days'), (current_date + interval '-5 days'), (current_date + interval '2 days'), 'ABIERTO', 3000, 3000, 1),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 3, (current_date + interval '15 days'), (current_date + interval '25 days'), (current_date + interval '28 days'), (current_date + interval '30 days'), 'PROGRAMADO', 3000, 0, 0),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 4, (current_date + interval '45 days'), (current_date + interval '55 days'), (current_date + interval '58 days'), (current_date + interval '60 days'), 'PROGRAMADO', 3000, 0, 0),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 5, (current_date + interval '75 days'), (current_date + interval '85 days'), (current_date + interval '88 days'), (current_date + interval '90 days'), 'PROGRAMADO', 3000, 0, 0),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 6, (current_date + interval '105 days'), (current_date + interval '115 days'), (current_date + interval '118 days'), (current_date + interval '120 days'), 'PROGRAMADO', 3000, 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO turno (grupo_id, periodo_id, cupo_id, orden_asignado, estado, criterio_asignacion, monto_estimado_cobro, confirmado_en) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), 1, 'COBRADO', 'SORTEO', 3000, now() - interval '30 days'),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 2), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 2), 2, 'EN_CURSO', 'SORTEO', 3000, NULL),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 3), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 3), 3, 'PROGRAMADO', 'SORTEO', 3000, NULL),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 4), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 4), 4, 'PROGRAMADO', 'SORTEO', 3000, NULL),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 5), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 5), 5, 'PROGRAMADO', 'SORTEO', 3000, NULL),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 6), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 6), 6, 'PROGRAMADO', 'SORTEO', 3000, NULL)
ON CONFLICT DO NOTHING;

-- Constitución del fondo de garantía: Bs 100 por participante, una sola vez, en el período 1. Es una obligación de tipo distinto al aporte, para que el reporte del grupo no las mezcle.
INSERT INTO obligacion_aporte (grupo_id, periodo_id, cupo_id, participante_id, tipo, monto_esperado, moneda, monto_pagado, monto_recargo, monto_condonado, monto_cubierto_garantia, estado, fecha_vencimiento, fecha_fin_gracia, fecha_pago_efectivo, dias_mora, version) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000001')), 'APORTE_FONDO_GARANTIA', 100.0, 'BOB', 100.0, 0, 0, 0, 'PAGADO', (current_date + interval '-43 days'), (current_date + interval '-40 days'), now() - interval '43 days', 0, 1),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 2), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000002')), 'APORTE_FONDO_GARANTIA', 100.0, 'BOB', 100.0, 0, 0, 0, 'PAGADO', (current_date + interval '-43 days'), (current_date + interval '-40 days'), now() - interval '43 days', 0, 1),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 3), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000003')), 'APORTE_FONDO_GARANTIA', 100.0, 'BOB', 100.0, 0, 0, 0, 'PAGADO', (current_date + interval '-43 days'), (current_date + interval '-40 days'), now() - interval '43 days', 0, 1),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 4), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000004')), 'APORTE_FONDO_GARANTIA', 100.0, 'BOB', 100.0, 0, 0, 0, 'PAGADO', (current_date + interval '-43 days'), (current_date + interval '-40 days'), now() - interval '43 days', 0, 1),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 5), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000005')), 'APORTE_FONDO_GARANTIA', 100.0, 'BOB', 100.0, 0, 0, 0, 'PAGADO', (current_date + interval '-43 days'), (current_date + interval '-40 days'), now() - interval '43 days', 0, 1),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 6), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000006')), 'APORTE_FONDO_GARANTIA', 100.0, 'BOB', 100.0, 0, 0, 0, 'PAGADO', (current_date + interval '-43 days'), (current_date + interval '-40 days'), now() - interval '43 days', 0, 1)
ON CONFLICT DO NOTHING;

-- Período 1: los seis aportes pagados. Es el camino feliz completo, el que termina en entrega acreditada.
INSERT INTO obligacion_aporte (grupo_id, periodo_id, cupo_id, participante_id, tipo, monto_esperado, moneda, monto_pagado, monto_recargo, monto_condonado, monto_cubierto_garantia, estado, fecha_vencimiento, fecha_fin_gracia, fecha_pago_efectivo, dias_mora, version, politica_mora_id) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000001')), 'APORTE_PERIODICO', 500.0, 'BOB', 500.0, 0, 0, 0, 'PAGADO', (current_date + interval '-35 days'), (current_date + interval '-32 days'), now() - interval '36 days', 0, 1, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1)),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 2), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000002')), 'APORTE_PERIODICO', 500.0, 'BOB', 500.0, 0, 0, 0, 'PAGADO', (current_date + interval '-35 days'), (current_date + interval '-32 days'), now() - interval '36 days', 0, 1, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1)),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 3), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000003')), 'APORTE_PERIODICO', 500.0, 'BOB', 500.0, 0, 0, 0, 'PAGADO', (current_date + interval '-35 days'), (current_date + interval '-32 days'), now() - interval '36 days', 0, 1, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1)),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 4), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000004')), 'APORTE_PERIODICO', 500.0, 'BOB', 500.0, 0, 0, 0, 'PAGADO', (current_date + interval '-35 days'), (current_date + interval '-32 days'), now() - interval '34 days', 0, 1, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1)),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 5), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000005')), 'APORTE_PERIODICO', 500.0, 'BOB', 500.0, 0, 0, 0, 'PAGADO', (current_date + interval '-35 days'), (current_date + interval '-32 days'), now() - interval '36 days', 0, 1, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1)),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 6), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000006')), 'APORTE_PERIODICO', 500.0, 'BOB', 500.0, 0, 0, 0, 'PAGADO', (current_date + interval '-35 days'), (current_date + interval '-32 days'), now() - interval '36 days', 0, 1, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1))
ON CONFLICT DO NOTHING;

-- Período 2: cinco pagados y uno cubierto por el fondo. La obligación de USR000004 tiene monto_recargo 10,00 (2 % de 500) y monto_cubierto_garantia 500,00; su saldo_pendiente derivado queda en 10,00 — el recargo NO lo cubre el fondo, lo debe el moroso.
INSERT INTO obligacion_aporte (grupo_id, periodo_id, cupo_id, participante_id, tipo, monto_esperado, moneda, monto_pagado, monto_recargo, monto_condonado, monto_cubierto_garantia, estado, fecha_vencimiento, fecha_fin_gracia, fecha_pago_efectivo, dias_mora, version, politica_mora_id) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 2), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000001')), 'APORTE_PERIODICO', 500.0, 'BOB', 500.0, 0, 0, 0, 'PAGADO', (current_date + interval '-8 days'), (current_date + interval '-5 days'), now() - interval '12 days', 0, 1, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1)),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 2), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 2), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000002')), 'APORTE_PERIODICO', 500.0, 'BOB', 500.0, 0, 0, 0, 'PAGADO', (current_date + interval '-8 days'), (current_date + interval '-5 days'), now() - interval '12 days', 0, 1, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1)),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 2), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 3), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000003')), 'APORTE_PERIODICO', 500.0, 'BOB', 500.0, 0, 0, 0, 'PAGADO', (current_date + interval '-8 days'), (current_date + interval '-5 days'), now() - interval '11 days', 0, 1, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1)),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 2), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 4), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000004')), 'APORTE_PERIODICO', 500.0, 'BOB', 0, 10.0, 0, 500.0, 'CUBIERTO_POR_GARANTIA', (current_date + interval '-8 days'), (current_date + interval '-5 days'), NULL, 8, 3, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1)),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 2), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 5), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000005')), 'APORTE_PERIODICO', 500.0, 'BOB', 500.0, 0, 0, 0, 'PAGADO', (current_date + interval '-8 days'), (current_date + interval '-5 days'), now() - interval '13 days', 0, 1, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1)),
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 2), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 6), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000006')), 'APORTE_PERIODICO', 500.0, 'BOB', 500.0, 0, 0, 0, 'PAGADO', (current_date + interval '-8 days'), (current_date + interval '-5 days'), now() - interval '10 days', 0, 1, (SELECT id FROM politica_mora WHERE grupo_id IS NULL LIMIT 1))
ON CONFLICT DO NOTHING;
