-- El camino feliz completo del período 1: fondo de garantía constituido, seis aportes acreditados, comisión con sus impuestos, entrega autorizada por una persona y ejecutada por otra, y factura emitida.
-- GENERADO desde seeders/dev/07-aportes-y-entrega.json — no editar a mano.

-- Constitución del fondo de garantía: Bs 100 por participante desde su saldo
INSERT INTO transaccion_billetera (tipo, estado, moneda, monto_total, grupo_id, origen_tipo, origen_id, canal, clave_idempotencia, hash_registro, ocurrida_en, registrada_en) VALUES
  ('REPOSICION_GARANTIA', 'APLICADA', 'BOB', 100.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND u.codigo_publico = 'USR000001'), 'APP', 'demo-fondo-inicial-01', '', now() - interval '43 days', now() - interval '43 days'),
  ('REPOSICION_GARANTIA', 'APLICADA', 'BOB', 100.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND u.codigo_publico = 'USR000002'), 'APP', 'demo-fondo-inicial-02', '', now() - interval '43 days', now() - interval '43 days'),
  ('REPOSICION_GARANTIA', 'APLICADA', 'BOB', 100.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND u.codigo_publico = 'USR000003'), 'APP', 'demo-fondo-inicial-03', '', now() - interval '43 days', now() - interval '43 days'),
  ('REPOSICION_GARANTIA', 'APLICADA', 'BOB', 100.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND u.codigo_publico = 'USR000004'), 'APP', 'demo-fondo-inicial-04', '', now() - interval '43 days', now() - interval '43 days'),
  ('REPOSICION_GARANTIA', 'APLICADA', 'BOB', 100.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND u.codigo_publico = 'USR000005'), 'APP', 'demo-fondo-inicial-05', '', now() - interval '43 days', now() - interval '43 days'),
  ('REPOSICION_GARANTIA', 'APLICADA', 'BOB', 100.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND u.codigo_publico = 'USR000006'), 'APP', 'demo-fondo-inicial-06', '', now() - interval '43 days', now() - interval '43 days')
ON CONFLICT (COALESCE(iniciada_por, '00000000-0000-0000-0000-000000000000'::uuid), origen_tipo, clave_idempotencia) DO NOTHING;

INSERT INTO movimiento_billetera (transaccion_id, cuenta_billetera_id, orden, sentido, monto, saldo_disponible_posterior, saldo_retenido_posterior, glosa, registrado_en) VALUES
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-01'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000001'), 1, 'DEBITO', 100.0, 1100.0, 0.0, 'Constitución del fondo de garantía del grupo', now() - interval '43 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-01'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'FDG-0000001'), 2, 'CREDITO', 100.0, 100.0, 0.0, 'Aporte inicial al fondo de garantía — USR000001', now() - interval '43 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-02'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000002'), 1, 'DEBITO', 100.0, 1100.0, 0.0, 'Constitución del fondo de garantía del grupo', now() - interval '43 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-02'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'FDG-0000001'), 2, 'CREDITO', 100.0, 200.0, 0.0, 'Aporte inicial al fondo de garantía — USR000002', now() - interval '43 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-03'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000003'), 1, 'DEBITO', 100.0, 1100.0, 0.0, 'Constitución del fondo de garantía del grupo', now() - interval '43 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-03'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'FDG-0000001'), 2, 'CREDITO', 100.0, 300.0, 0.0, 'Aporte inicial al fondo de garantía — USR000003', now() - interval '43 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-04'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000004'), 1, 'DEBITO', 100.0, 500.0, 0.0, 'Constitución del fondo de garantía del grupo', now() - interval '43 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-04'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'FDG-0000001'), 2, 'CREDITO', 100.0, 400.0, 0.0, 'Aporte inicial al fondo de garantía — USR000004', now() - interval '43 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-05'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000005'), 1, 'DEBITO', 100.0, 1900.0, 0.0, 'Constitución del fondo de garantía del grupo', now() - interval '43 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-05'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'FDG-0000001'), 2, 'CREDITO', 100.0, 500.0, 0.0, 'Aporte inicial al fondo de garantía — USR000005', now() - interval '43 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-06'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000006'), 1, 'DEBITO', 100.0, 1100.0, 0.0, 'Constitución del fondo de garantía del grupo', now() - interval '43 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-06'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'FDG-0000001'), 2, 'CREDITO', 100.0, 600.0, 0.0, 'Aporte inicial al fondo de garantía — USR000006', now() - interval '43 days')
ON CONFLICT DO NOTHING;

-- El libro del fondo: cada constitución deja su saldo resultante
INSERT INTO movimiento_fondo (fondo_id, asiento_contable_id, tipo, monto, saldo_resultante, referencia_tipo, referencia_id, descripcion, fecha, registrado_por) VALUES
  ((SELECT f.id FROM fondo_garantia f JOIN grupo g ON g.id = f.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01'), NULL, 'CONSTITUCION', 100.0, 100.0, 'obligacion_aporte', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND pe.numero = 1 AND u.codigo_publico = 'USR000001'), 'Constitución inicial del fondo — USR000001', now() - interval '43 days', NULL),
  ((SELECT f.id FROM fondo_garantia f JOIN grupo g ON g.id = f.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01'), NULL, 'CONSTITUCION', 100.0, 200.0, 'obligacion_aporte', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND pe.numero = 1 AND u.codigo_publico = 'USR000002'), 'Constitución inicial del fondo — USR000002', now() - interval '43 days', NULL),
  ((SELECT f.id FROM fondo_garantia f JOIN grupo g ON g.id = f.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01'), NULL, 'CONSTITUCION', 100.0, 300.0, 'obligacion_aporte', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND pe.numero = 1 AND u.codigo_publico = 'USR000003'), 'Constitución inicial del fondo — USR000003', now() - interval '43 days', NULL),
  ((SELECT f.id FROM fondo_garantia f JOIN grupo g ON g.id = f.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01'), NULL, 'CONSTITUCION', 100.0, 400.0, 'obligacion_aporte', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND pe.numero = 1 AND u.codigo_publico = 'USR000004'), 'Constitución inicial del fondo — USR000004', now() - interval '43 days', NULL),
  ((SELECT f.id FROM fondo_garantia f JOIN grupo g ON g.id = f.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01'), NULL, 'CONSTITUCION', 100.0, 500.0, 'obligacion_aporte', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND pe.numero = 1 AND u.codigo_publico = 'USR000005'), 'Constitución inicial del fondo — USR000005', now() - interval '43 days', NULL),
  ((SELECT f.id FROM fondo_garantia f JOIN grupo g ON g.id = f.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01'), NULL, 'CONSTITUCION', 100.0, 600.0, 'obligacion_aporte', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_FONDO_GARANTIA' AND pe.numero = 1 AND u.codigo_publico = 'USR000006'), 'Constitución inicial del fondo — USR000006', now() - interval '43 days', NULL)
ON CONFLICT DO NOTHING;

-- Aportes del período 1 pagados con saldo de billetera: no hay proveedor externo, la contrapartida es interna
INSERT INTO pago (obligacion_id, intento_pago_id, proveedor_id, monto, moneda, monto_comision_proveedor, monto_neto_acreditado, canal, estado, fecha_hora_pago, fecha_hora_acreditacion, referencia_proveedor, pagador_nombre, pagador_documento, cuenta_origen_enmascarada, registrado_por, es_manual, clave_idempotencia) VALUES
  ((SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000001'), NULL, NULL, 500.0, 'BOB', 0.0, 500.0, 'BILLETERA_MOVIL', 'ACREDITADO', now() - interval '36 days', now() - interval '36 days', 'INT-P1-01', NULL, NULL, '****4001', NULL, FALSE, 'demo-pago-p1-01'),
  ((SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000002'), NULL, NULL, 500.0, 'BOB', 0.0, 500.0, 'BILLETERA_MOVIL', 'ACREDITADO', now() - interval '36 days', now() - interval '36 days', 'INT-P1-02', NULL, NULL, '****4002', NULL, FALSE, 'demo-pago-p1-02'),
  ((SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000003'), NULL, NULL, 500.0, 'BOB', 0.0, 500.0, 'BILLETERA_MOVIL', 'ACREDITADO', now() - interval '36 days', now() - interval '36 days', 'INT-P1-03', NULL, NULL, '****4003', NULL, FALSE, 'demo-pago-p1-03'),
  ((SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000004'), NULL, NULL, 500.0, 'BOB', 0.0, 500.0, 'BILLETERA_MOVIL', 'ACREDITADO', now() - interval '36 days', now() - interval '36 days', 'INT-P1-04', NULL, NULL, '****4004', NULL, FALSE, 'demo-pago-p1-04'),
  ((SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000005'), NULL, NULL, 500.0, 'BOB', 0.0, 500.0, 'BILLETERA_MOVIL', 'ACREDITADO', now() - interval '36 days', now() - interval '36 days', 'INT-P1-05', NULL, NULL, '****4005', NULL, FALSE, 'demo-pago-p1-05'),
  ((SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000006'), NULL, NULL, 500.0, 'BOB', 0.0, 500.0, 'BILLETERA_MOVIL', 'ACREDITADO', now() - interval '36 days', now() - interval '36 days', 'INT-P1-06', NULL, NULL, '****4006', NULL, FALSE, 'demo-pago-p1-06')
ON CONFLICT (obligacion_id, clave_idempotencia) DO NOTHING;

INSERT INTO transaccion_billetera (tipo, estado, moneda, monto_total, grupo_id, origen_tipo, origen_id, canal, clave_idempotencia, hash_registro, ocurrida_en, registrada_en) VALUES
  ('APORTE_A_GRUPO', 'APLICADA', 'BOB', 500.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000001'), 'APP', 'demo-aporte-p1-01', '', now() - interval '36 days', now() - interval '36 days'),
  ('APORTE_A_GRUPO', 'APLICADA', 'BOB', 500.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000002'), 'APP', 'demo-aporte-p1-02', '', now() - interval '36 days', now() - interval '36 days'),
  ('APORTE_A_GRUPO', 'APLICADA', 'BOB', 500.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000003'), 'APP', 'demo-aporte-p1-03', '', now() - interval '36 days', now() - interval '36 days'),
  ('APORTE_A_GRUPO', 'APLICADA', 'BOB', 500.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000004'), 'APP', 'demo-aporte-p1-04', '', now() - interval '36 days', now() - interval '36 days'),
  ('APORTE_A_GRUPO', 'APLICADA', 'BOB', 500.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000005'), 'APP', 'demo-aporte-p1-05', '', now() - interval '36 days', now() - interval '36 days'),
  ('APORTE_A_GRUPO', 'APLICADA', 'BOB', 500.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'OBLIGACION_APORTE', (SELECT o.id FROM obligacion_aporte o JOIN participante p ON p.id = o.participante_id JOIN usuario u ON u.id = p.usuario_id JOIN periodo pe ON pe.id = o.periodo_id WHERE o.tipo = 'APORTE_PERIODICO' AND pe.numero = 1 AND u.codigo_publico = 'USR000006'), 'APP', 'demo-aporte-p1-06', '', now() - interval '36 days', now() - interval '36 days')
ON CONFLICT (COALESCE(iniciada_por, '00000000-0000-0000-0000-000000000000'::uuid), origen_tipo, clave_idempotencia) DO NOTHING;

INSERT INTO movimiento_billetera (transaccion_id, cuenta_billetera_id, orden, sentido, monto, saldo_disponible_posterior, saldo_retenido_posterior, glosa, registrado_en) VALUES
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-01'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000001'), 1, 'DEBITO', 500.0, 600.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01', now() - interval '36 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-01'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'GRP-0000001'), 2, 'CREDITO', 500.0, 500.0, 0.0, 'Aporte del período 1 — USR000001', now() - interval '36 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-02'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000002'), 1, 'DEBITO', 500.0, 600.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01', now() - interval '36 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-02'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'GRP-0000001'), 2, 'CREDITO', 500.0, 1000.0, 0.0, 'Aporte del período 1 — USR000002', now() - interval '36 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-03'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000003'), 1, 'DEBITO', 500.0, 600.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01', now() - interval '36 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-03'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'GRP-0000001'), 2, 'CREDITO', 500.0, 1500.0, 0.0, 'Aporte del período 1 — USR000003', now() - interval '36 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-04'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000004'), 1, 'DEBITO', 500.0, 0.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01', now() - interval '36 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-04'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'GRP-0000001'), 2, 'CREDITO', 500.0, 2000.0, 0.0, 'Aporte del período 1 — USR000004', now() - interval '36 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-05'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000005'), 1, 'DEBITO', 500.0, 1400.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01', now() - interval '36 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-05'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'GRP-0000001'), 2, 'CREDITO', 500.0, 2500.0, 0.0, 'Aporte del período 1 — USR000005', now() - interval '36 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-06'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000006'), 1, 'DEBITO', 500.0, 600.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01', now() - interval '36 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-06'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'GRP-0000001'), 2, 'CREDITO', 500.0, 3000.0, 0.0, 'Aporte del período 1 — USR000006', now() - interval '36 days')
ON CONFLICT DO NOTHING;

INSERT INTO entrega_fondo (grupo_id, periodo_id, turno_id, cupo_id, beneficiario_participante_id, cuenta_destino_id, monto_bolsa_bruto, total_deducciones, monto_neto_a_entregar, monto_efectivamente_entregado, moneda, estado, metodo_desembolso, fecha_programada, fecha_autorizacion, fecha_entrega, autorizada_por, ejecutada_por, comprobante_url, hash_comprobante, observaciones, version) VALUES
  ((SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM periodo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT t.id FROM turno t JOIN grupo g ON g.id = t.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND t.orden_asignado = 1), (SELECT id FROM cupo WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND numero = 1), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000001')), NULL, 3000.0, 10.5, 2989.5, 2989.5, 'BOB', 'CONFIRMADA', 'COMPENSACION_INTERNA', (current_date + interval '-30 days'), now() - interval '30 days', now() - interval '30 days', (SELECT id FROM usuario WHERE codigo_publico = 'USR000009'), (SELECT id FROM usuario WHERE codigo_publico = 'USR000008'), 'https://almacen.pasanaku.test/entregas/demo-p1.pdf', encode(digest('entrega-demo-p1', 'sha256'), 'hex'), 'Acreditación en la billetera del beneficiario, sin salida de custodia.', 3)
ON CONFLICT DO NOTHING;

-- Las ocho reglas del catálogo mínimo 09 evaluadas, siete bloqueantes y una informativa, todas aprobadas
INSERT INTO validacion_pre_entrega (entrega_id, regla_id, resultado, valor_esperado, valor_obtenido, es_bloqueante, omitida_por, justificacion_omision, evaluada_en) VALUES
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), (SELECT id FROM regla_entrega WHERE codigo = 'BOLSA_COMPLETA'), 'APROBADA', '3000.00', '3000.00', TRUE, NULL, NULL, now() - interval '30 days'),
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), (SELECT id FROM regla_entrega WHERE codigo = 'BENEFICIARIO_KYC_VIGENTE'), 'APROBADA', 'VIGENTE', 'VIGENTE', TRUE, NULL, NULL, now() - interval '30 days'),
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), (SELECT id FROM regla_entrega WHERE codigo = 'CUENTA_DESTINO_VERIFICADA'), 'APROBADA', 'VERIFICADA', 'BILLETERA PROPIA', TRUE, NULL, NULL, now() - interval '30 days'),
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), (SELECT id FROM regla_entrega WHERE codigo = 'SIN_BLOQUEO_DE_AUTORIDAD'), 'APROBADA', '0 bloqueos', '0 bloqueos', TRUE, NULL, NULL, now() - interval '30 days'),
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), (SELECT id FROM regla_entrega WHERE codigo = 'DEUDA_PROPIA_DEDUCIDA'), 'APROBADA', '0.00', '0.00', TRUE, NULL, NULL, now() - interval '30 days'),
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), (SELECT id FROM regla_entrega WHERE codigo = 'COMISION_DEVENGADA'), 'APROBADA', '10.50', '10.50', TRUE, NULL, NULL, now() - interval '30 days'),
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), (SELECT id FROM regla_entrega WHERE codigo = 'ENCAJE_CUMPLIDO'), 'APROBADA', 'ratio >= 1', 'ratio = 1.000000', TRUE, NULL, NULL, now() - interval '30 days'),
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), (SELECT id FROM regla_entrega WHERE codigo = 'CONFIRMACION_DATOS'), 'APROBADA', 'confirmado', 'confirmado', FALSE, NULL, NULL, now() - interval '30 days')
ON CONFLICT DO NOTHING;

-- La cotización se congela y se muestra ANTES de cobrar: el usuario ve el número antes de que le toquen la bolsa
INSERT INTO cotizacion_comision (concepto_tarifa_id, tarifario_id, referencia_tipo, referencia_id, monto_base, monto_comision, monto_impuesto, monto_total, moneda, desglose, valida_hasta, mostrada_al_usuario_en, aceptada_en, clave_idempotencia) VALUES
  ((SELECT id FROM concepto_tarifa WHERE codigo = 'COM_ENTREGA' AND tarifario_id = (SELECT id FROM tarifario WHERE codigo = 'GENERAL' AND version = 1)), (SELECT id FROM tarifario WHERE codigo = 'GENERAL' AND version = 1), 'ENTREGA_FONDO', (SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), 3000.0, 8.81, 1.69, 10.5, 'BOB', '{"tramo": "0 a 3000", "porcentaje": 0.35, "bruto": 10.5, "piso": 10, "techo": 50, "iva": 1.37, "it": 0.32, "neto_plataforma": 8.81}'::jsonb, now() - interval '29 days', now() - interval '31 days', now() - interval '30 days', 'demo-cotizacion-entrega-p1')
ON CONFLICT (referencia_id, clave_idempotencia) DO NOTHING;

INSERT INTO devengo_comision (concepto_tarifa_id, tarifario_id, cotizacion_id, grupo_id, participante_id, usuario_obligado_id, asiento_contable_id, referencia_tipo, referencia_id, monto_base, monto_comision, monto_descuento, monto_impuesto, monto_total, moneda, estado, fecha_devengo, periodo_contable, clave_idempotencia) VALUES
  ((SELECT id FROM concepto_tarifa WHERE codigo = 'COM_ENTREGA' AND tarifario_id = (SELECT id FROM tarifario WHERE codigo = 'GENERAL' AND version = 1)), (SELECT id FROM tarifario WHERE codigo = 'GENERAL' AND version = 1), (SELECT id FROM cotizacion_comision WHERE clave_idempotencia = 'demo-cotizacion-entrega-p1'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), (SELECT id FROM participante WHERE grupo_id = (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01') AND usuario_id = (SELECT id FROM usuario WHERE codigo_publico = 'USR000001')), (SELECT id FROM usuario WHERE codigo_publico = 'USR000001'), NULL, 'ENTREGA_FONDO', (SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), 3000.0, 8.81, 0.0, 1.69, 10.5, 'BOB', 'COBRADO', now() - interval '30 days', '2026-01', 'demo-devengo-entrega-p1')
ON CONFLICT (COALESCE(grupo_id, '00000000-0000-0000-0000-000000000000'::uuid), clave_idempotencia) DO NOTHING;

INSERT INTO calculo_impuesto (devengo_id, impuesto_id, base_imponible, alicuota_aplicada, monto_impuesto, incluido_en_precio, periodo_fiscal) VALUES
  ((SELECT id FROM devengo_comision WHERE clave_idempotencia = 'demo-devengo-entrega-p1'), (SELECT id FROM impuesto WHERE codigo = 'IVA' ORDER BY vigente_desde DESC LIMIT 1), 10.5, 0.13, 1.37, TRUE, '2026-01'),
  ((SELECT id FROM devengo_comision WHERE clave_idempotencia = 'demo-devengo-entrega-p1'), (SELECT id FROM impuesto WHERE codigo = 'IT' ORDER BY vigente_desde DESC LIMIT 1), 10.5, 0.03, 0.32, TRUE, '2026-01')
ON CONFLICT DO NOTHING;

INSERT INTO deduccion_entrega (entrega_id, tipo, descripcion, monto, referencia_origen_id, es_obligatoria, aplicada_en, revertida_en) VALUES
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), 'COMISION_PLATAFORMA', 'Comisión por cobro de turno, impuestos incluidos', 10.5, NULL, TRUE, now() - interval '30 days', NULL)
ON CONFLICT DO NOTHING;

INSERT INTO transaccion_billetera (tipo, estado, moneda, monto_total, grupo_id, origen_tipo, origen_id, canal, clave_idempotencia, hash_registro, ocurrida_en, registrada_en) VALUES
  ('ENTREGA_DE_FONDO', 'APLICADA', 'BOB', 3000.0, (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'ENTREGA_FONDO', (SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id WHERE pe.numero = 1), 'BATCH', 'demo-entrega-p1', '', now() - interval '30 days', now() - interval '30 days')
ON CONFLICT (COALESCE(iniciada_por, '00000000-0000-0000-0000-000000000000'::uuid), origen_tipo, clave_idempotencia) DO NOTHING;

INSERT INTO movimiento_billetera (transaccion_id, cuenta_billetera_id, orden, sentido, monto, saldo_disponible_posterior, saldo_retenido_posterior, glosa, registrado_en) VALUES
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-entrega-p1'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'GRP-0000001'), 1, 'DEBITO', 3000.0, 0.0, 0.0, 'Entrega de la bolsa del período 1 al turno 1', now() - interval '30 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-entrega-p1'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000001'), 2, 'CREDITO', 2989.5, 3589.5, 0.0, 'Bolsa del período 1 acreditada, neta de comisión', now() - interval '30 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-entrega-p1'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'SYS-INGRESOS'), 3, 'CREDITO', 8.81, 8.81, 0.0, 'Comisión por cobro de turno, neta de impuestos', now() - interval '30 days'),
  ((SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-entrega-p1'), (SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'SYS-IMPUESTOS'), 4, 'CREDITO', 1.69, 1.69, 0.0, 'IVA e IT retenidos sobre la comisión de entrega', now() - interval '30 days')
ON CONFLICT DO NOTHING;

INSERT INTO cargo_comision (devengo_id, deduccion_entrega_id, transaccion_id, obligacion_id, forma_cobro, monto_cobrado, moneda, estado, intentos, ultimo_error, cobrado_en) VALUES
  ((SELECT id FROM devengo_comision WHERE clave_idempotencia = 'demo-devengo-entrega-p1'), (SELECT id FROM deduccion_entrega WHERE tipo = 'COMISION_PLATAFORMA' LIMIT 1), (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-entrega-p1'), NULL, 'DEDUCCION_DE_ENTREGA', 10.5, 'BOB', 'COBRADO', 1, NULL, now() - interval '30 days')
ON CONFLICT DO NOTHING;

INSERT INTO historial_estado_entrega (entrega_id, estado_anterior, estado_nuevo, motivo, ejecutado_por, fecha_hora) VALUES
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), 'PROGRAMADA', 'LISTA_PARA_ENTREGA', 'Las siete validaciones previas bloqueantes dieron APROBADA', NULL, now() - interval '31 days'),
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), 'LISTA_PARA_ENTREGA', 'AUTORIZADA', 'Autorizada por riesgos con el permiso ENTREGA_AUTORIZAR', (SELECT id FROM usuario WHERE codigo_publico = 'USR000009'), now() - interval '30 days'),
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), 'AUTORIZADA', 'ENTREGADA', 'Ejecutada por tesorería: acreditación en la billetera del beneficiario', (SELECT id FROM usuario WHERE codigo_publico = 'USR000008'), now() - interval '30 days'),
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), 'ENTREGADA', 'CONFIRMADA', 'El beneficiario confirmó la recepción desde la app', NULL, now() - interval '29 days')
ON CONFLICT DO NOTHING;

INSERT INTO confirmacion_recepcion (entrega_id, estado, monto_confirmado, token_confirmacion_id, confirmada_en, plazo_limite, autoconfirmada_por_vencimiento, ip_confirmacion, comentario) VALUES
  ((SELECT e.id FROM entrega_fondo e JOIN periodo pe ON pe.id = e.periodo_id JOIN grupo g ON g.id = e.grupo_id WHERE g.codigo_publico = 'GRP-DEMO-01' AND pe.numero = 1), 'CONFIRMADA_POR_BENEFICIARIO', 2989.5, NULL, now() - interval '29 days', now() - interval '23 days', FALSE, '190.129.0.11', 'Recibido conforme.')
ON CONFLICT DO NOTHING;

INSERT INTO datos_facturacion (usuario_id, tipo_documento, numero_documento, razon_social, email_envio, es_predeterminado, verificado, actualizado_en) VALUES
  ((SELECT id FROM usuario WHERE codigo_publico = 'USR000001'), 'CI', '9000001', 'María Elena Quispe Mamani', 'demo1@pasanaku.test', TRUE, TRUE, now() - interval '45 days')
ON CONFLICT DO NOTHING;

INSERT INTO factura_electronica (devengo_id, usuario_id, datos_facturacion_id, lote_envio_sin_id, evento_significativo_id, nit_emisor, sucursal, punto_venta, numero_factura, cuf, cufd, codigo_control, fecha_emision, monto_total, monto_iva, monto_no_sujeto, moneda, estado_fiscal, url_pdf, url_xml, hash_documento, qr_verificacion, leyenda, anulada_en, motivo_anulacion) VALUES
  ((SELECT id FROM devengo_comision WHERE clave_idempotencia = 'demo-devengo-entrega-p1'), (SELECT id FROM usuario WHERE codigo_publico = 'USR000001'), (SELECT id FROM datos_facturacion WHERE numero_documento = '9000001'), NULL, NULL, '1099887766', 0, 0, 1, 'DEMO-CUF-0000000000000001', 'DEMO-CUFD-0000000000000001', NULL, now() - interval '30 days', 10.5, 1.37, 0.0, 'BOB', 'VALIDADA', 'https://almacen.pasanaku.test/facturas/demo-1.pdf', 'https://almacen.pasanaku.test/facturas/demo-1.xml', encode(digest('factura-demo-1', 'sha256'), 'hex'), 'https://siat.impuestos.gob.bo/consulta/QR?nit=1099887766&cuf=DEMO-CUF-0000000000000001', 'Ley N° 453: El proveedor debe suministrar información completa y veraz.', NULL, NULL)
ON CONFLICT DO NOTHING;
