-- El libro contable de partida doble derivado de la billetera: un asiento por transacción, con sus movimientos al debe y al haber. Más los saldos diarios sellados y los estados de cuenta emitidos.
-- GENERADO desde seeders/dev/11-contabilidad-y-saldos.json — no editar a mano.

-- Un asiento por transacción, en estado CONFIRMADO. El número es BIGSERIAL: lo asigna la base y no se repite.
INSERT INTO asiento_contable (fecha, glosa, origen_tipo, origen_id, grupo_id, estado, asiento_reversa_id, registrado_por) VALUES
  (now() - interval '44 days', 'Emisión de dinero electrónico por recarga', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-recarga-01'), NULL, 'CONFIRMADO', NULL, NULL),
  (now() - interval '44 days', 'Emisión de dinero electrónico por recarga', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-recarga-02'), NULL, 'CONFIRMADO', NULL, NULL),
  (now() - interval '44 days', 'Emisión de dinero electrónico por recarga', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-recarga-03'), NULL, 'CONFIRMADO', NULL, NULL),
  (now() - interval '44 days', 'Emisión de dinero electrónico por recarga', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-recarga-04'), NULL, 'CONFIRMADO', NULL, NULL),
  (now() - interval '44 days', 'Emisión de dinero electrónico por recarga', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-recarga-05'), NULL, 'CONFIRMADO', NULL, NULL),
  (now() - interval '44 days', 'Emisión de dinero electrónico por recarga', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-recarga-06'), NULL, 'CONFIRMADO', NULL, NULL),
  (now() - interval '43 days', 'Constitución del fondo de garantía del grupo', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-01'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '43 days', 'Constitución del fondo de garantía del grupo', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-02'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '43 days', 'Constitución del fondo de garantía del grupo', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-03'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '43 days', 'Constitución del fondo de garantía del grupo', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-04'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '43 days', 'Constitución del fondo de garantía del grupo', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-05'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '43 days', 'Constitución del fondo de garantía del grupo', 'BILLETERA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-fondo-inicial-06'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '36 days', 'Aporte del participante a la bolsa del grupo', 'PAGO', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-01'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '36 days', 'Aporte del participante a la bolsa del grupo', 'PAGO', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-02'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '36 days', 'Aporte del participante a la bolsa del grupo', 'PAGO', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-03'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '36 days', 'Aporte del participante a la bolsa del grupo', 'PAGO', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-04'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '36 days', 'Aporte del participante a la bolsa del grupo', 'PAGO', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-05'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '36 days', 'Aporte del participante a la bolsa del grupo', 'PAGO', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p1-06'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '30 days', 'Entrega de la bolsa al beneficiario del turno, neta de comisión', 'ENTREGA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-entrega-p1'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '12 days', 'Aporte del participante a la bolsa del grupo', 'PAGO', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p2-01'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '12 days', 'Aporte del participante a la bolsa del grupo', 'PAGO', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p2-02'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '11 days', 'Aporte del participante a la bolsa del grupo', 'PAGO', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p2-03'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '13 days', 'Aporte del participante a la bolsa del grupo', 'PAGO', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p2-05'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '10 days', 'Aporte del participante a la bolsa del grupo', 'PAGO', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-aporte-p2-06'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL),
  (now() - interval '3 days', 'Cobertura del fondo de garantía por aporte impago', 'COBERTURA', (SELECT id FROM transaccion_billetera WHERE clave_idempotencia = 'demo-cobertura-p2-04'), (SELECT id FROM grupo WHERE codigo_publico = 'GRP-DEMO-01'), 'CONFIRMADO', NULL, NULL)
ON CONFLICT DO NOTHING;

-- Las partidas de cada asiento. El total del debe iguala al del haber en cada uno; si no, el asiento no debería existir.
INSERT INTO movimiento_contable (asiento_id, cuenta_id, debe, haber, descripcion) VALUES
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-01'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 0.0, 1200.0, 'Recarga acreditada — referencia QR-000001-INI'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-01'), (SELECT id FROM cuenta_contable WHERE codigo = '1.1.01'), 1200.0, 0.0, 'Contrapartida en la cuenta puente de custodia — recarga 01'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-02'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 0.0, 1200.0, 'Recarga acreditada — referencia QR-000002-INI'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-02'), (SELECT id FROM cuenta_contable WHERE codigo = '1.1.01'), 1200.0, 0.0, 'Contrapartida en la cuenta puente de custodia — recarga 02'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-03'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 0.0, 1200.0, 'Recarga acreditada — referencia QR-000003-INI'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-03'), (SELECT id FROM cuenta_contable WHERE codigo = '1.1.01'), 1200.0, 0.0, 'Contrapartida en la cuenta puente de custodia — recarga 03'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-04'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 0.0, 600.0, 'Recarga acreditada — referencia QR-000004-INI'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-04'), (SELECT id FROM cuenta_contable WHERE codigo = '1.1.01'), 600.0, 0.0, 'Contrapartida en la cuenta puente de custodia — recarga 04'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-05'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 0.0, 2000.0, 'Recarga acreditada — referencia QR-000005-INI'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-05'), (SELECT id FROM cuenta_contable WHERE codigo = '1.1.01'), 2000.0, 0.0, 'Contrapartida en la cuenta puente de custodia — recarga 05'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-06'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 0.0, 1200.0, 'Recarga acreditada — referencia QR-000006-INI'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-recarga-06'), (SELECT id FROM cuenta_contable WHERE codigo = '1.1.01'), 1200.0, 0.0, 'Contrapartida en la cuenta puente de custodia — recarga 06'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-01'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 100.0, 0.0, 'Constitución del fondo de garantía del grupo'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-01'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.03'), 0.0, 100.0, 'Aporte inicial al fondo de garantía — USR000001'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-02'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 100.0, 0.0, 'Constitución del fondo de garantía del grupo'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-02'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.03'), 0.0, 100.0, 'Aporte inicial al fondo de garantía — USR000002'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-03'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 100.0, 0.0, 'Constitución del fondo de garantía del grupo'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-03'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.03'), 0.0, 100.0, 'Aporte inicial al fondo de garantía — USR000003'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-04'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 100.0, 0.0, 'Constitución del fondo de garantía del grupo'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-04'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.03'), 0.0, 100.0, 'Aporte inicial al fondo de garantía — USR000004'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-05'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 100.0, 0.0, 'Constitución del fondo de garantía del grupo'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-05'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.03'), 0.0, 100.0, 'Aporte inicial al fondo de garantía — USR000005'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-06'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 100.0, 0.0, 'Constitución del fondo de garantía del grupo'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-fondo-inicial-06'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.03'), 0.0, 100.0, 'Aporte inicial al fondo de garantía — USR000006'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-01'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 500.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-01'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 1 — USR000001'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-02'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 500.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-02'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 1 — USR000002'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-03'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 500.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-03'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 1 — USR000003'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-04'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 500.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-04'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 1 — USR000004'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-05'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 500.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-05'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 1 — USR000005'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-06'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 500.0, 0.0, 'Aporte del período 1 al grupo GRP-DEMO-01'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p1-06'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 1 — USR000006'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-entrega-p1'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 3000.0, 0.0, 'Entrega de la bolsa del período 1 al turno 1'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-entrega-p1'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.01'), 0.0, 2989.5, 'Bolsa del período 1 acreditada, neta de comisión'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-entrega-p1'), (SELECT id FROM cuenta_contable WHERE codigo = '4.1.01'), 0.0, 8.81, 'Comisión por cobro de turno, neta de impuestos'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-entrega-p1'), (SELECT id FROM cuenta_contable WHERE codigo = '2.2.01'), 0.0, 1.37, 'IVA débito fiscal sobre la comisión de entrega'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-entrega-p1'), (SELECT id FROM cuenta_contable WHERE codigo = '2.2.02'), 0.0, 0.32, 'Impuesto a las transacciones sobre la comisión de entrega'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p2-01'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 2 cobrado por QR interoperable — USR000001'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p2-01'), (SELECT id FROM cuenta_contable WHERE codigo = '1.1.01'), 500.0, 0.0, 'Ingreso a custodia por cobro QR del aporte — USR000001'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p2-02'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 2 cobrado por QR interoperable — USR000002'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p2-02'), (SELECT id FROM cuenta_contable WHERE codigo = '1.1.01'), 500.0, 0.0, 'Ingreso a custodia por cobro QR del aporte — USR000002'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p2-03'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 2 cobrado por QR interoperable — USR000003'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p2-03'), (SELECT id FROM cuenta_contable WHERE codigo = '1.1.01'), 500.0, 0.0, 'Ingreso a custodia por cobro QR del aporte — USR000003'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p2-05'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 2 cobrado por QR interoperable — USR000005'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p2-05'), (SELECT id FROM cuenta_contable WHERE codigo = '1.1.01'), 500.0, 0.0, 'Ingreso a custodia por cobro QR del aporte — USR000005'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p2-06'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 2 cobrado por QR interoperable — USR000006'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-aporte-p2-06'), (SELECT id FROM cuenta_contable WHERE codigo = '1.1.01'), 500.0, 0.0, 'Ingreso a custodia por cobro QR del aporte — USR000006'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-cobertura-p2-04'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.03'), 500.0, 0.0, 'Cobertura del aporte impago del período 2 — USR000004'),
  ((SELECT a.id FROM asiento_contable a JOIN transaccion_billetera t ON t.id = a.origen_id WHERE t.clave_idempotencia = 'demo-cobertura-p2-04'), (SELECT id FROM cuenta_contable WHERE codigo = '2.1.02'), 0.0, 500.0, 'Aporte del período 2 cubierto por el fondo de garantía')
ON CONFLICT DO NOTHING;

-- Por qué el enlace queda en un solo sentido
-- Intencionalmente NO se actualiza transaccion_billetera.asiento_contable_id.
-- La tabla es append-only (R-AUD-01) y el trigger rechaza cualquier UPDATE, así
-- que el enlace hacia atrás no se puede cerrar desde un seeder. El vínculo vive
-- en asiento_contable.origen_id, que apunta a la transacción y alcanza para
-- reconstruir el libro. En la aplicación, el caso de uso debe crear el asiento
-- ANTES de insertar la transacción y pasarle el id ya generado: después de
-- insertarla, esa columna es inmutable.
SELECT 1;

-- Lo consumido del límite mensual de recarga por cada titular en la ventana en que recargó
INSERT INTO consumo_limite (cuenta_billetera_id, limite_id, ventana_inicio, ventana_fin, monto_acumulado, cantidad_acumulada, actualizado_en) VALUES
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000001'), (SELECT id FROM limite_operativo_billetera WHERE concepto = 'RECARGA' AND ventana = 'MES' AND nivel_debida_diligencia = (SELECT nivel_debida_diligencia FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000001') LIMIT 1), date_trunc('month', now() - interval '44 days'), date_trunc('month', now() - interval '44 days') + interval '1 month', 1200.0, 1, now() - interval '44 days'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000002'), (SELECT id FROM limite_operativo_billetera WHERE concepto = 'RECARGA' AND ventana = 'MES' AND nivel_debida_diligencia = (SELECT nivel_debida_diligencia FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000002') LIMIT 1), date_trunc('month', now() - interval '44 days'), date_trunc('month', now() - interval '44 days') + interval '1 month', 1200.0, 1, now() - interval '44 days'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000003'), (SELECT id FROM limite_operativo_billetera WHERE concepto = 'RECARGA' AND ventana = 'MES' AND nivel_debida_diligencia = (SELECT nivel_debida_diligencia FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000003') LIMIT 1), date_trunc('month', now() - interval '44 days'), date_trunc('month', now() - interval '44 days') + interval '1 month', 1200.0, 1, now() - interval '44 days'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000004'), (SELECT id FROM limite_operativo_billetera WHERE concepto = 'RECARGA' AND ventana = 'MES' AND nivel_debida_diligencia = (SELECT nivel_debida_diligencia FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000004') LIMIT 1), date_trunc('month', now() - interval '44 days'), date_trunc('month', now() - interval '44 days') + interval '1 month', 600.0, 1, now() - interval '44 days'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000005'), (SELECT id FROM limite_operativo_billetera WHERE concepto = 'RECARGA' AND ventana = 'MES' AND nivel_debida_diligencia = (SELECT nivel_debida_diligencia FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000005') LIMIT 1), date_trunc('month', now() - interval '44 days'), date_trunc('month', now() - interval '44 days') + interval '1 month', 2000.0, 1, now() - interval '44 days'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000006'), (SELECT id FROM limite_operativo_billetera WHERE concepto = 'RECARGA' AND ventana = 'MES' AND nivel_debida_diligencia = (SELECT nivel_debida_diligencia FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000006') LIMIT 1), date_trunc('month', now() - interval '44 days'), date_trunc('month', now() - interval '44 days') + interval '1 month', 1200.0, 1, now() - interval '44 days')
ON CONFLICT DO NOTHING;

-- Cierre de saldos del día anterior, una fila por cuenta. Es append-only: corregir un saldo es agregar el día siguiente, nunca editar este.
INSERT INTO saldo_diario_billetera (cuenta_billetera_id, fecha, saldo_disponible, saldo_retenido, cantidad_movimientos, hash_registro, hash_anterior, cerrado_en) VALUES
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000001'), (current_date + interval '-1 days'), 3589.5, 0.0, 4, encode(digest('saldo-diario-BOB-0000001', 'sha256'), 'hex'), NULL, now() - interval '18 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000002'), (current_date + interval '-1 days'), 600.0, 0.0, 3, encode(digest('saldo-diario-BOB-0000002', 'sha256'), 'hex'), NULL, now() - interval '18 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000003'), (current_date + interval '-1 days'), 600.0, 0.0, 3, encode(digest('saldo-diario-BOB-0000003', 'sha256'), 'hex'), NULL, now() - interval '18 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000004'), (current_date + interval '-1 days'), 0.0, 0.0, 3, encode(digest('saldo-diario-BOB-0000004', 'sha256'), 'hex'), NULL, now() - interval '18 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000005'), (current_date + interval '-1 days'), 1400.0, 0.0, 3, encode(digest('saldo-diario-BOB-0000005', 'sha256'), 'hex'), NULL, now() - interval '18 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000006'), (current_date + interval '-1 days'), 600.0, 0.0, 3, encode(digest('saldo-diario-BOB-0000006', 'sha256'), 'hex'), NULL, now() - interval '18 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'FDG-0000001'), (current_date + interval '-1 days'), 100.0, 0.0, 7, encode(digest('saldo-diario-FDG-0000001', 'sha256'), 'hex'), NULL, now() - interval '18 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'GRP-0000001'), (current_date + interval '-1 days'), 3000.0, 0.0, 13, encode(digest('saldo-diario-GRP-0000001', 'sha256'), 'hex'), NULL, now() - interval '18 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'SYS-CUSTODIA'), (current_date + interval '-1 days'), -9900.0, 0.0, 11, encode(digest('saldo-diario-SYS-CUSTODIA', 'sha256'), 'hex'), NULL, now() - interval '18 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'SYS-IMPUESTOS'), (current_date + interval '-1 days'), 1.69, 0.0, 1, encode(digest('saldo-diario-SYS-IMPUESTOS', 'sha256'), 'hex'), NULL, now() - interval '18 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'SYS-INGRESOS'), (current_date + interval '-1 days'), 8.81, 0.0, 1, encode(digest('saldo-diario-SYS-INGRESOS', 'sha256'), 'hex'), NULL, now() - interval '18 hours')
ON CONFLICT DO NOTHING;

-- El extracto que el cliente descarga, con su hash para poder verificar después que no se alteró
INSERT INTO estado_cuenta_billetera (cuenta_billetera_id, periodo_desde, periodo_hasta, saldo_inicial, total_creditos, total_debitos, saldo_final, cantidad_movimientos, url_archivo, hash_archivo, emitido_en, entregado_en) VALUES
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000001'), (current_date + interval '-45 days'), (current_date + interval '-1 days'), 0.0, 4189.5, 600.0, 3589.5, 4, 'https://almacen.pasanaku.test/extractos/BOB-0000001.pdf', encode(digest('extracto-BOB-0000001', 'sha256'), 'hex'), now() - interval '12 hours', now() - interval '12 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000002'), (current_date + interval '-45 days'), (current_date + interval '-1 days'), 0.0, 1200.0, 600.0, 600.0, 3, 'https://almacen.pasanaku.test/extractos/BOB-0000002.pdf', encode(digest('extracto-BOB-0000002', 'sha256'), 'hex'), now() - interval '12 hours', now() - interval '12 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000003'), (current_date + interval '-45 days'), (current_date + interval '-1 days'), 0.0, 1200.0, 600.0, 600.0, 3, 'https://almacen.pasanaku.test/extractos/BOB-0000003.pdf', encode(digest('extracto-BOB-0000003', 'sha256'), 'hex'), now() - interval '12 hours', now() - interval '12 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000004'), (current_date + interval '-45 days'), (current_date + interval '-1 days'), 0.0, 600.0, 600.0, 0.0, 3, 'https://almacen.pasanaku.test/extractos/BOB-0000004.pdf', encode(digest('extracto-BOB-0000004', 'sha256'), 'hex'), now() - interval '12 hours', now() - interval '12 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000005'), (current_date + interval '-45 days'), (current_date + interval '-1 days'), 0.0, 2000.0, 600.0, 1400.0, 3, 'https://almacen.pasanaku.test/extractos/BOB-0000005.pdf', encode(digest('extracto-BOB-0000005', 'sha256'), 'hex'), now() - interval '12 hours', now() - interval '12 hours'),
  ((SELECT id FROM cuenta_billetera WHERE numero_cuenta = 'BOB-0000006'), (current_date + interval '-45 days'), (current_date + interval '-1 days'), 0.0, 1200.0, 600.0, 600.0, 3, 'https://almacen.pasanaku.test/extractos/BOB-0000006.pdf', encode(digest('extracto-BOB-0000006', 'sha256'), 'hex'), now() - interval '12 hours', now() - interval '12 hours')
ON CONFLICT DO NOTHING;
